import {env} from 'cloudflare:workers';import {getChatGPTUser} from '@/app/chatgpt-auth';import {D1DecisionLedger} from '@/db/ledger';import {loadPractice,commandPractice,savePractice} from '@/db/practice-sessions';import {transitionPractice,type PracticeAction} from '@/lib/practice-session';import {readBoundedText} from '@/lib/strategy-ai-server';import {z} from 'zod';
const headers={'Cache-Control':'no-store'};const controls=z.discriminatedUnion('action',[
 z.object({action:z.literal('confirm'),strategy:z.object({version:z.number(),kind:z.enum(['scheduled','threshold','allocation','accumulate','sell_threshold','sell_below','price_band','rebalance','portfolio']),direction:z.string().max(1500),symbol:z.string().max(8),amountCents:z.number(),reserveCents:z.number(),intervalHours:z.number(),thresholdCents:z.number(),sellThresholdCents:z.number().optional(),targetBps:z.number(),driftBps:z.number(),maxMovementBps:z.number(),mode:z.enum(['approval','automatic']),targets:z.array(z.object({symbol:z.string().max(8),targetBps:z.number()}).strict()).max(3).optional()}).strict()}).strict(),
 z.object({action:z.literal('price'),symbol:z.string().max(8),priceCents:z.number().int().min(1).max(100000000)}).strict(),
 z.object({action:z.literal('price_source'),source:z.enum(['fixture','market'])}).strict(),
 z.object({action:z.literal('approve'),id:z.string().uuid()}).strict(),z.object({action:z.literal('decline'),id:z.string().uuid()}).strict(),z.object({action:z.literal('scenario'),scenario:z.enum(['healthy','stale','cash','daily','concentration'])}).strict(),z.object({action:z.literal('background'),enabled:z.boolean()}).strict(),
 ...(['authorize','start','pause','revoke','run','advance','refresh_quote','refresh','reset'] as const).map(action=>z.object({action:z.literal(action)}).strict())
]);const input=z.object({revision:z.number().int().nonnegative(),command:controls,trigger:z.enum(['manual','foreground']).optional()}).strict();
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Saved practice storage is unavailable.'},{status:503,headers});try{const m=await new D1DecisionLedger(env.DB).getMandate(user.userId);let session=await loadPractice(env.DB,user.userId);if(m){const next=transitionPractice(session,m,{action:'refresh'});if(JSON.stringify(next)!==JSON.stringify(session)){if(await savePractice(env.DB,user.userId,session,next))session=next;else session=await loadPractice(env.DB,user.userId);}}if(new URL(request.url).searchParams.get('download')==='1')return Response.json({...session,notice:session.priceSource==='market'?'Saved fake-money practice using read-only indicative underlying stock quotes. No market fills, blockchain transactions, or live execution.':'Saved simulation with fake funds and fixture prices. No blockchain transactions or live financial evidence.'},{headers:{...headers,'Content-Disposition':'attachment; filename="stock-steward-practice.json"','X-Content-Type-Options':'nosniff'}});return Response.json({session,backgroundAvailable:!!env.STEWARD_WORKER_KEY&&env.STEWARD_RUNNER_ENABLED==='true'},{headers});}catch{return Response.json({error:'Saved practice is unavailable. Your rules were not changed.'},{status:503,headers});}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Saved practice storage is unavailable.'},{status:503,headers});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin.'},{status:403,headers});let body;try{body=input.parse(JSON.parse(await readBoundedText(request,6000)));}catch{return Response.json({error:'Invalid practice command.'},{status:400,headers});}try{const m=await new D1DecisionLedger(env.DB).getMandate(user.userId);if(!m)throw Error('Save your boundaries first.');if(body.command.action==='background'&&body.command.enabled&&(!env.STEWARD_WORKER_KEY||env.STEWARD_RUNNER_ENABLED!=='true'))throw Error('Background runner is not configured.');const trigger=body.command.action==='run'&&body.trigger==='foreground'?'foreground':'manual';const session=await commandPractice(env.DB,user.userId,body.revision,body.command as PracticeAction,m,Date.now(),trigger);return Response.json({session},{headers});}catch(e){const conflict=e instanceof Error&&e.message==='PRACTICE_CONFLICT';const message=e instanceof Error&&/^(Save |Confirm |Authorize |Start |Revoke |Approval expired|This purchase|Invalid simulated|Background runner|Test clock|Fixture quote|Manual prices|Fixture scenarios|Live price|Choose a stock|Portfolio target|Include every held)/.test(e.message)?e.message:conflict?'Practice changed in another tab. Refresh before trying again.':'Practice command could not be completed. Refresh your session.';return Response.json({error:message},{status:conflict?409:400,headers});}}
