import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {loadGoal,saveGoal} from '@/db/goal-plans';
import {readBoundedText} from '@/lib/strategy-ai-server';
import {z} from 'zod';
const headers={'Cache-Control':'no-store'};
const input=z.object({revision:z.number().int().nonnegative(),plan:z.object({name:z.string().trim().min(1).max(80),targetCents:z.number().int().positive().max(10000000000),currentCents:z.number().int().nonnegative().max(10000000000),monthlyCents:z.number().int().nonnegative().max(10000000000),months:z.number().int().min(1).max(600),comfort:z.enum(['cautious','balanced','comfortable']),startedAt:z.string().datetime()}).strict()}).strict();
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Your saved plan is unavailable.'},{status:503,headers});try{return Response.json({goal:await loadGoal(env.DB,user.userId)},{headers});}catch{return Response.json({error:'Your saved plan is temporarily unavailable. Try again.'},{status:503,headers});}}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Your saved plan is unavailable.'},{status:503,headers});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin.'},{status:403,headers});let body;try{body=input.parse(JSON.parse(await readBoundedText(request,4000)));}catch{return Response.json({error:'Check your goal details and amounts.'},{status:400,headers});}try{return Response.json({goal:await saveGoal(env.DB,user.userId,body.revision,body.plan)},{headers});}catch(e){const conflict=e instanceof Error&&e.message==='GOAL_CONFLICT';return Response.json({error:conflict?'Your plan changed in another tab. Reload the saved plan before saving.':'Could not save your plan. Your draft is still here.'},{status:conflict?409:503,headers});}}
