import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/legal-layout";

export const metadata: Metadata = { title: "Privacy · Stock Steward" };

export default function PrivacyPage() {
  return <LegalLayout eyebrow="PRIVACY" title="What we keep. Why we keep it." updated="29 September 2026">
    <p className="legal-lead">Stock Steward is an independent project that helps account owners set stock-purchase limits and inspect decision receipts. This notice explains the data used by the current preview and wallet observations.</p>
    <LegalSection title="Who to contact"><p>Stock Steward operates under the Stock Steward name. For privacy questions or data requests, email <a href="mailto:stocksteward.support@gmail.com">stocksteward.support@gmail.com</a>. The project is in early access; users can practice with simulated funds and observe public wallets.</p></LegalSection>
    <LegalSection title="Sign-in and workspace records"><p>Our hosting and sign-in service provides a site-specific user identifier and your sign-in email. Stock Steward uses the identifier to keep your saved mandate and any decision receipts separate from other users’ records. Your mandate contains the symbols and limits you choose, its version, and when it was saved. We do not ask for your brokerage password.</p></LegalSection>
    <LegalSection title="Broker data and decision receipts"><p>The current interface uses simulated practice records and public wallet observations. Earlier account integrations may have left historical records and encrypted connection credentials. These are not used by the current workspace and are included in reviewed deletion requests. Stored financial observations may be sensitive. The landing-page walkthrough is illustrative.</p></LegalSection>
    <LegalSection title="Wallet observations"><p>Connecting a browser wallet or entering a public address sends that address to the Robinhood Chain RPC to read balances. Official asset metadata comes from Robinhood. Selecting Observe & save stores the address, supported holdings, raw balances, indicative quotes and timestamps, corporate-action multipliers, block and mandate version under your signed-in site identity. These records remain until reviewed deletion; disconnecting does not erase them. Quote services receive requested symbols. Manually requested autonomy readiness checks also store the address, saved mandate version, infrastructure evidence, pending checks and reasons for blocking execution. No wallet delegation or spending grant is installed by these checks. Opt-in monitoring stores public addresses, intervals, revisions, run timestamps and linked evidence. Transaction watches store public hashes and RPC status. A Cloudflare Cron Worker wakes the read-only endpoint and receives summary counts, not holdings or addresses. Pause monitoring before deletion requests. A per-user cooldown timestamp limits read frequency. Service providers may process request metadata. Optional wallet-control verification asks you to sign a domain-bound message with a five-minute nonce. We store that message, address and verification timestamp, but do not persist the signature. This grants no spending authority. Route checks store the USDG amount, official token, pool evidence, block, quoted output and blockers in readiness receipts. No private key is requested.</p></LegalSection><LegalSection title="Why we use it, and who handles it"><p>We use saved records to apply your practice rules, explain decisions and show wallet evidence. The site host provides sign-in, compute and database storage. Robinhood data services provide public chain and stock-token evidence. Cloudflare Workers AI interprets directions when requested. These services may process information outside your country. Stock Steward does not sell your data or use it for advertising.</p></LegalSection>
    <LegalSection title="Practice sessions"><p>Practice saves your confirmed strategy, direction notes, fake cash and holdings, simulated prices, permission expiry and the latest 50 receipts under your signed-in site identity. These are simulated records, not real financial balances. Optional background practice uses the authenticated worker to check saved rules with fake funds; The Cloudflare Worker receives aggregate counts, not your direction or balances. Pause or revoke stops future background practice. Sessions survive reloads. Download practice receipts to export the saved session. Reset clears prior fake balances and receipts while retaining confirmed rules; account deletion review includes the saved practice session.</p></LegalSection>
    <LegalSection title="AI direction interpretation"><p>When you click Interpret, your direction is sent through our server to Cloudflare Workers AI to suggest draft rules. Wallet keys, wallet balances and connection credentials are not sent. We do not store your prompt in the AI usage table; it records your site identifier, request counts and cooldown times. Review suggestions before confirming. AI cannot authorize spending.</p></LegalSection><LegalSection title="Security and permissions"><p>Workspace access is checked against your signed-in site identifier. Wallet ownership verification and practice permission are separate from live spending authority. Wallet connection alone does not authorize a trade. The current deployment does not enable live spending. Existing connection credentials remain encrypted and outside the browser.</p></LegalSection>
    <LegalSection title="Retention and deletion"><p>Saved records have no automatic expiry. You can request reviewed deletion from your <a href="/account">Account page</a> or email <a href="mailto:stocksteward.support@gmail.com">stocksteward.support@gmail.com</a> from your sign-in email. Do not send keys, passwords, tokens or identity documents. We verify the request and any unresolved historical outcomes before erasing records. Deleting workspace records does not delete your wallet or hosting sign-in account.</p></LegalSection>
    <LegalSection title="Your choices and updates"><p>You can read the public pages without signing in or connecting a wallet. You choose whether to save a mandate and whether to enable or revoke practice permission. Contact us at the address above to ask about access, correction, or deletion of Stock Steward data. We will update this notice before using data for a materially different purpose and change the revision date when it changes.</p></LegalSection>
  </LegalLayout>;
}

