import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/legal-layout";

export const metadata: Metadata = { title: "Privacy · Stock Steward" };

export default function PrivacyPage() {
  return <LegalLayout eyebrow="PRIVACY" title="What we keep. Why we keep it." updated="26 September 2026">
    <p className="legal-lead">Stock Steward is an independent project that helps account owners set stock-purchase limits and inspect decision receipts. This notice explains the data used by the current preview and the broker connection being prepared.</p>
    <LegalSection title="Who to contact"><p>Stock Steward operates under the Stock Steward name. For privacy questions or data requests, email <a href="mailto:stocksteward.support@gmail.com">stocksteward.support@gmail.com</a>. The project is in early access; eligible users can connect their own Alpaca accounts.</p></LegalSection>
    <LegalSection title="Sign-in and workspace records"><p>Our hosting and sign-in service provides a site-specific user identifier and your sign-in email. Stock Steward uses the identifier to keep your saved mandate and any decision receipts separate from other users’ records. Your mandate contains the symbols and limits you choose, its version, and when it was saved. We do not ask for your brokerage password.</p></LegalSection>
    <LegalSection title="Broker data and decision receipts"><p>If you choose to connect an eligible Alpaca account, Alpaca handles its own sign-in and consent screen. Stock Steward will receive an account identifier and access token for the permissions you grant. Checks may read balances, buying power, positions, asset eligibility, quotes and their timestamps, open orders, and recent fills. Partial observations keep account balances, positions, open orders, market status and pending rule checks. Receipts keep the observed figures, the mandate version, each rule result, the reason for a hold or approval, and any later order events. These records can reveal sensitive financial information. The landing-page walkthrough is illustrative and does not use your account.</p></LegalSection>
    <LegalSection title="Wallet observations"><p>Connecting a browser wallet or entering a public address sends that address to the Robinhood Chain RPC to read balances. Official asset metadata comes from Robinhood. Selecting Observe & save stores the address, supported holdings, raw balances, indicative quotes and timestamps, corporate-action multipliers, block and mandate version under your signed-in site identity. These records remain until reviewed deletion; disconnecting does not erase them. Quote services receive requested symbols. Manually requested autonomy readiness checks also store the address, saved mandate version, infrastructure evidence, pending checks and reasons for blocking execution. No wallet delegation or spending grant is installed by these checks. Opt-in monitoring stores public addresses, intervals, revisions, run timestamps and linked evidence. Transaction watches store public hashes and RPC status. GitHub Actions wakes the read-only worker and receives summary counts, not holdings or addresses. Pause monitoring before deletion requests. A per-user cooldown timestamp limits read frequency. Service providers may process request metadata. Optional wallet-control verification asks you to sign a domain-bound message with a five-minute nonce. We store that message, address and verification timestamp, but do not persist the signature. This grants no spending authority. Route checks store the USDG amount, official token, pool evidence, block, quoted output and blockers in readiness receipts. No private key is requested.</p></LegalSection><LegalSection title="Why we use it, and who handles it"><p>We use these records to run the limits you save, explain decisions, show your trail, and, only after separate trading permission and exact owner approval, process an order when that feature is enabled. The site host provides sign-in, compute, and database storage. Alpaca processes brokerage authentication, market and account data, and any broker order. These providers may process information outside your country. Stock Steward does not sell your account data or use it for advertising.</p></LegalSection>
    <LegalSection title="Security and permissions"><p>Broker tokens are encrypted before storage and used in server-side requests. Workspace access is checked against your signed-in site identifier. Read access and trading permission are separate choices. A connection alone does not turn on automatic trading, and this deployment has no configured live order access.</p></LegalSection>
    <LegalSection title="Retention and deletion"><p>Saved mandates, partial observations and receipts currently have no automatic expiry; they remain so you can inspect what Stock Steward observed and did. Disconnecting removes the locally stored broker token, but leaves those records and does not itself revoke permission in Alpaca’s settings. You can submit a deletion request from your signed-in <a href="/account">Account page</a>. It is recorded under your site identity and reviewed before anything is erased. You can also email <a href="mailto:stocksteward.support@gmail.com?subject=Stock%20Steward%20data%20deletion%20request">stocksteward.support@gmail.com</a> from your sign-in email. Do not send a password, account number, identity document, or token. We will verify the request, check for an unresolved order, and explain what we can erase and whether any record must be kept for a specific legal or dispute reason. Deleting Stock Steward data does not delete your Alpaca account or the hosting provider’s sign-in account.</p></LegalSection>
    <LegalSection title="Your choices and updates"><p>You can read the public pages without signing in or connecting a broker. You choose whether to save a mandate and whether to grant or withdraw broker access. Contact us at the address above to ask about access, correction, or deletion of Stock Steward data. We will update this notice before using data for a materially different purpose and change the revision date when it changes.</p></LegalSection>
  </LegalLayout>;
}

