import test from 'node:test';import assert from 'node:assert/strict';import {encodeAbiParameters,parseAbiParameters,encodeFunctionData,parseAbi} from 'viem';import {inspectRoute,routeAmount,VENUE} from './chain-route.ts';
const address='0x'+'a'.repeat(40),token='0x'+'b'.repeat(40),hash='0x'+'c'.repeat(64);
const enc=(types:string,values:unknown[])=>encodeAbiParameters(parseAbiParameters(types),values as never);
function mock(options:{wrong?:boolean;emptyCode?:boolean;manager?:boolean;outage?:boolean;reorg?:boolean;inactive?:boolean}={}){let blocks=0;const pinned:string[]=[];const fetcher=(async(url:string,init?:RequestInit)=>{
 if(String(url).includes('/rhj/assets'))return Response.json({assets:[{tokenSymbol:'AAPL',status:options.inactive?'ASSET_STATUS_HALTED':'ASSET_STATUS_ACTIVE',deployments:[{chainId:4663,contractAddress:token}]}]});const q=JSON.parse(String(init?.body));let result:unknown;
 if(q.method==='eth_chainId')result=options.wrong?'0x1':'0x1237';else if(q.method==='eth_blockNumber')result='0x123';else if(q.method==='eth_getBlockByNumber'){blocks++;result={number:'0x123',hash:options.reorg&&blocks>1?'0x'+'d'.repeat(64):hash,timestamp:'0x'+Math.floor(Date.now()/1000).toString(16)};}
 else if(q.method==='eth_getCode'){pinned.push(q.params[1]);result=options.emptyCode?'0x':'0x1234';}
 else if(q.method==='eth_call'){pinned.push(q.params[1]);const {to,data}=q.params[0];const selector=data.slice(0,10);if(selector==='0x313ce567')result=enc('uint8',[to===VENUE.settlement?6:18]);else if(selector==='0x70a08231')result=enc('uint256',[5000000n]);else if(selector===encodeFunctionData({abi:parseAbi(['function poolManager() view returns(address)']),functionName:'poolManager'}))result=enc('address',[options.manager?token:VENUE.manager]);else if(to===VENUE.state){const liq=encodeFunctionData({abi:parseAbi(['function getLiquidity(bytes32) view returns(uint128)']),functionName:'getLiquidity',args:[hash as `0x${string}`]}).slice(0,10);result=selector===liq?enc('uint128',[1000n]):enc('uint160,int24,uint24,uint24',[2n**96n,0,0,3000]);}else if(to===VENUE.quoter){if(options.outage)return Response.json({id:q.id,error:{code:-1,message:'Unavailable'}});result=enc('uint256,uint256',[1000000000000000n,45000n]);}}
 return Response.json({jsonrpc:'2.0',id:q.id,result});}) as typeof fetch;return {fetcher,pinned};}
test('direct quotes use official tokens, pin every contract read and keep spending blocked',async()=>{const m=mock();const r=await inspectRoute(address,'AAPL','1',50,m.fetcher);assert.equal(r.inputRaw,'1000000');assert.equal(r.probes.length,4);assert.equal(r.best?.outputTokens,'0.001');assert.equal(r.minimumOutputRaw,'995000000000000');assert.equal(r.executionEnabled,false);assert.ok(m.pinned.every(b=>b==='0x123'));assert.ok(Date.parse(r.expiresAt)<=Date.parse(r.blockAt)+30000);});
test('wrong chains, absent code, counterfeit manager and block reorg fail closed',async()=>{for(const options of [{wrong:true},{emptyCode:true},{manager:true},{reorg:true},{inactive:true}])await assert.rejects(inspectRoute(address,'AAPL','1',50,mock(options).fetcher));});
test('quoter outage means unavailable evidence, not nonexistent liquidity',async()=>{const r=await inspectRoute(address,'AAPL','1',50,mock({outage:true}).fetcher);assert.equal(r.best,null);assert.ok(r.probes.every(p=>p.state==='unavailable'));assert.ok(r.blockers.some(b=>b.includes('Other pools')));});
test('settlement amounts reject hidden rounding, zero, exponent and excess precision',()=>{assert.equal(routeAmount('0.000001',6),1n);for(const a of ['0','1e3','-1','1.0000001','01',' 1'])assert.throws(()=>routeAmount(a,6));});
