import test from 'node:test';import assert from 'node:assert/strict';import {encodeEventTopics,encodeAbiParameters,parseAbi,parseAbiParameters,keccak256,type Hex} from 'viem';
import {reconcileDirectFill} from './chain-fill-proof.ts';import {routerCandidate} from './router-candidate.ts';import {poolIdentity,VENUE,type RouteEvidence} from './chain-route.ts';
const owner=('0x'+'a'.repeat(40)) as Hex,token=('0x'+'3'.repeat(40)) as Hex,hash='0x'+'b'.repeat(64),blockHash='0x'+'c'.repeat(64),finalHash='0x'+'d'.repeat(64);
function fixture(){const route={id:'fixture-only',chainId:4663,address:owner,settlement:VENUE.settlement,token,inputRaw:'1000000',minimumOutputRaw:'123',best:{state:'quoted',outputRaw:'150',fee:3000,tickSpacing:60,poolId:poolIdentity(token,3000,60).poolId},blockHash,blockAt:'2026-09-27T12:00:00Z',observedAt:'2026-09-27T12:00:00Z',expiresAt:'2026-09-27T12:00:20Z'} as RouteEvidence,candidate=routerCandidate(route,1);const transfer=(address:Hex,from:Hex,to:Hex,value:bigint,index:number)=>({address,topics:encodeEventTopics({abi:parseAbi(['event Transfer(address indexed from,address indexed to,uint256 value)']),eventName:'Transfer',args:{from,to}}),data:encodeAbiParameters(parseAbiParameters('uint256'),[value]),transactionHash:hash,blockHash,logIndex:'0x'+index.toString(16)});const tx={hash,from:owner,to:candidate.to,input:candidate.data,value:'0x0',blockHash,blockNumber:'0x10'},receipt={transactionHash:hash,blockHash,blockNumber:'0x10',status:'0x1',logs:[transfer(VENUE.settlement,owner,VENUE.manager,1000000n,1),transfer(token,VENUE.manager,owner,140n,2)]};return {route,tx,receipt,transfer};}
function provider(f:ReturnType<typeof fixture>,override:Record<string,unknown>={}){return (async(_url,init)=>{const q=JSON.parse(String(init?.body));assert.ok(['eth_chainId','eth_getTransactionByHash','eth_getTransactionReceipt','eth_getBlockByNumber','eth_blockNumber','eth_getCode'].includes(q.method));let result:unknown;if(q.method==='eth_chainId')result='0x1237';if(q.method==='eth_getTransactionByHash')result=f.tx;if(q.method==='eth_getTransactionReceipt')result=f.receipt;if(q.method==='eth_blockNumber')result='0x20';if(q.method==='eth_getCode')result='0x6000';if(q.method==='eth_getBlockByNumber')result=q.params[0]==='finalized'||q.params[0]==='0x20'?{number:'0x20',hash:finalHash}:{number:'0x10',hash:blockHash,timestamp:'0x'+Math.floor(Date.parse('2026-09-27T12:00:10Z')/1000).toString(16)};if(Object.hasOwn(override,q.method))result=override[q.method];return Response.json({jsonrpc:'2.0',id:q.id,result});}) as typeof fetch;}
test('exact finalized direct-router fill verifies input, output and transfer provenance',async()=>{const f=fixture(),proof=await reconcileDirectFill(f.route,1,hash,keccak256('0x6000'),provider(f));assert.equal(proof.outcome,'verified_fill');assert.equal(proof.actualInputRaw,'1000000');assert.equal(proof.actualOutputRaw,'140');assert.equal(proof.delegatedAccountVerified,false);});
test('outer success alone, missing logs and transfer changes cannot settle spending',async()=>{for(const mutate of [(f:ReturnType<typeof fixture>)=>f.receipt.logs=[],(f:ReturnType<typeof fixture>)=>f.receipt.logs[1]=f.transfer(token,VENUE.manager,owner,122n,2),(f:ReturnType<typeof fixture>)=>f.receipt.logs[0]=f.transfer(VENUE.settlement,owner,VENUE.manager,1000001n,1),(f:ReturnType<typeof fixture>)=>f.receipt.logs[1]=f.transfer(token,owner,owner,140n,2),(f:ReturnType<typeof fixture>)=>f.receipt.logs.push(f.receipt.logs[1]),(f:ReturnType<typeof fixture>)=>f.receipt.logs[1].blockHash=finalHash]){const f=fixture();mutate(f);assert.equal((await reconcileDirectFill(f.route,1,hash,keccak256('0x6000'),provider(f))).outcome,'unknown');}});
test('wrong chain, target, calldata, account, code, finality and canonical block stay unresolved',async()=>{for(const change of [{eth_chainId:'0x1'},{eth_getTransactionByHash:null},{eth_getBlockByNumber:null},{eth_getCode:'0x6001'},{eth_getTransactionReceipt:null}]){const f=fixture();assert.equal((await reconcileDirectFill(f.route,1,hash,keccak256('0x6000'),provider(f,change))).outcome,'unknown');}for(const mutate of [(f:ReturnType<typeof fixture>)=>f.tx.from=token,(f:ReturnType<typeof fixture>)=>f.tx.to=token,(f:ReturnType<typeof fixture>)=>f.tx.input=(f.tx.input+'00') as Hex,(f:ReturnType<typeof fixture>)=>f.tx.value='0x1']){const f=fixture();mutate(f);assert.equal((await reconcileDirectFill(f.route,1,hash,keccak256('0x6000'),provider(f))).outcome,'unknown');}});
test('only an exact finalized reverted transaction can establish a revert',async()=>{const f=fixture();f.receipt.status='0x0';f.receipt.logs=[];const p=await reconcileDirectFill(f.route,1,hash,keccak256('0x6000'),provider(f));assert.equal(p.outcome,'reverted');assert.equal(p.actualInputRaw,null);assert.equal(p.canonicalFinalized,true);});
