import {encodeFunctionData,decodeFunctionResult,encodeAbiParameters,keccak256,parseAbi,parseUnits,formatUnits,type Address,type Hex} from 'viem';
import {CHAIN,registry} from './robinhood-chain.ts';
export const VENUE={manager:'0x8366a39cc670b4001a1121b8f6a443a643e40951',quoter:'0x8dc178efb8111bb0973dd9d722ebeff267c98f94',state:'0xf3334192d15450cdd385c8b70e03f9a6bd9e673b',settlement:'0x5fc5360d0400a0fd4f2af552add042d716f1d168'} as const;
const ZERO='0x0000000000000000000000000000000000000000' as Address;
const stateAbi=parseAbi(['function getLiquidity(bytes32) view returns (uint128)','function getSlot0(bytes32) view returns (uint160,int24,uint24,uint24)','function poolManager() view returns (address)']);
const quoteAbi=parseAbi(['function poolManager() view returns (address)','function quoteExactInputSingle(((address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks) poolKey,bool zeroForOne,uint128 exactAmount,bytes hookData) params) returns (uint256 amountOut,uint256 gasEstimate)']);
const ercAbi=parseAbi(['function decimals() view returns (uint8)','function balanceOf(address) view returns (uint256)']);
export type PoolProbe={fee:number;tickSpacing:number;poolId:string;state:'quoted'|'uninitialized'|'no_active_liquidity'|'unavailable';liquidity?:string;outputRaw?:string;outputTokens?:string;quoterGas?:string;reason:string};
export type RouteEvidence={id:string;chainId:number;address:string;symbol:string;token:string;settlement:string;input:string;inputRaw:string;settlementDecimals:number;block:string;blockHash:string;blockAt:string;observedAt:string;expiresAt:string;balanceRaw:string;slippageBps:number;probes:PoolProbe[];best:PoolProbe|null;minimumOutputRaw:string|null;executionEnabled:false;coverage:string;blockers:string[]};
export function routeAmount(amount:string,decimals:number){if(!/^(?:0|[1-9]\d{0,5})(?:\.\d{1,18})?$/.test(amount)||amount.split('.')[1]?.length>decimals)throw new Error('Enter an exact positive USDG token amount.');const raw=parseUnits(amount,decimals);if(raw<=0n||raw>2n**128n-1n)throw new Error('Amount outside supported range.');return raw;}
export function poolIdentity(token:Address,fee:number,tickSpacing:number){const currencies=[VENUE.settlement,token.toLowerCase()].sort() as [Address,Address];const key={currency0:currencies[0],currency1:currencies[1],fee,tickSpacing,hooks:ZERO};const poolId=keccak256(encodeAbiParameters([{type:'address'},{type:'address'},{type:'uint24'},{type:'int24'},{type:'address'}],[key.currency0,key.currency1,fee,tickSpacing,ZERO]));return {key,poolId,zeroForOne:key.currency0===VENUE.settlement};}
export async function inspectRoute(address:string,symbol:string,amount:string,slippageBps=50,fetcher:typeof fetch=fetch):Promise<RouteEvidence>{
 if(!/^0x[0-9a-f]{40}$/i.test(address)||! /^[A-Z0-9.-]{1,12}$/.test(symbol)||!Number.isInteger(slippageBps)||slippageBps<1||slippageBps>100)throw new Error('Invalid route request.');
 let serial=0;async function rpc(method:string,params:unknown[]){const id=++serial;const r=await fetcher(CHAIN.rpc,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id,method,params}),signal:AbortSignal.timeout(12000),cache:'no-store'});if(!r.ok)throw new Error('Route RPC unavailable');const b=await r.json() as {id:number;result:unknown;error?:unknown};if(b.id!==id||b.error||b.result===undefined)throw new Error('Route RPC evidence unavailable');return b.result;}
 if(BigInt(String(await rpc('eth_chainId',[])))!==BigInt(CHAIN.id))throw new Error('Wrong network');
 const block=String(await rpc('eth_blockNumber',[]));if(!/^0x[0-9a-f]+$/i.test(block))throw new Error('Invalid block');
 const header=await rpc('eth_getBlockByNumber',[block,false]) as {hash?:string;number?:string;timestamp?:string};if(header.number!==block||!/^0x[0-9a-f]{64}$/i.test(header.hash??'')||!/^0x[0-9a-f]+$/i.test(header.timestamp??'')||Math.abs(Date.now()-Number(BigInt(header.timestamp!))*1000)>120000)throw new Error('Current canonical block unavailable');
 const r=await fetcher('https://api.robinhood.com/rhj/assets',{signal:AbortSignal.timeout(12000),cache:'no-store'});if(!r.ok)throw new Error('Official asset registry unavailable');const asset=registry(await r.json()).find(t=>t.symbol===symbol);if(!asset||asset.status!=='ASSET_STATUS_ACTIVE')throw new Error('Active official stock token not found');
 async function call(to:Address,abi:typeof ercAbi|typeof stateAbi|typeof quoteAbi,name:string,args:unknown[]=[]){const data=encodeFunctionData({abi,functionName:name,args} as never);const raw=await rpc('eth_call',[{to,data},block]);if(typeof raw!=='string'||!/^0x(?:[0-9a-f]{2})+$/i.test(raw))throw new Error('Contract response unavailable');return decodeFunctionResult({abi,functionName:name,data:raw as Hex} as never) as unknown;}
 for(const contract of [VENUE.manager,VENUE.quoter,VENUE.state,VENUE.settlement,asset.contract]){const code=await rpc('eth_getCode',[contract,block]);if(typeof code!=='string'||!/^0x(?:[0-9a-f]{2})+$/i.test(code))throw new Error('Required contract unavailable');}
 for(const [target,abi] of [[VENUE.state,stateAbi],[VENUE.quoter,quoteAbi]] as const){if(String(await call(target,abi,'poolManager')).toLowerCase()!==VENUE.manager)throw new Error('Venue manager mismatch');}
 const decimals=Number(await call(VENUE.settlement,ercAbi,'decimals'));if(!Number.isInteger(decimals)||decimals<0||decimals>18)throw new Error('Settlement decimals unavailable');const raw=routeAmount(amount,decimals);
 const stockDecimals=Number(await call(asset.contract as Address,ercAbi,'decimals'));if(stockDecimals!==18)throw new Error('Stock token decimals mismatch');
 const balance=await call(VENUE.settlement,ercAbi,'balanceOf',[address]);const probes:PoolProbe[]=await Promise.all([[100,1],[500,10],[3000,60],[10000,200]].map(async([fee,tickSpacing])=>{const {key,poolId,zeroForOne}=poolIdentity(asset.contract as Address,fee,tickSpacing);const probe:PoolProbe={fee,tickSpacing,poolId,state:'unavailable',reason:'RPC or quote unavailable; no absence of liquidity inferred.'};try{const slot=await call(VENUE.state,stateAbi,'getSlot0',[poolId]) as readonly [bigint,number,number,number];if(slot[0]===0n)return {...probe,state:'uninitialized' as const,reason:'This exact pool key is not initialized at the observed block.'};const liquidity=await call(VENUE.state,stateAbi,'getLiquidity',[poolId]) as bigint;probe.liquidity=liquidity.toString();if(liquidity===0n)return {...probe,state:'no_active_liquidity' as const,reason:'No active liquidity at the current tick for this key.'};const [output,gas]=await call(VENUE.quoter,quoteAbi,'quoteExactInputSingle',[{poolKey:key,zeroForOne,exactAmount:raw,hookData:'0x'}]) as readonly [bigint,bigint];if(output<=0n)throw new Error('Empty quote');return {...probe,state:'quoted' as const,outputRaw:output.toString(),outputTokens:formatUnits(output,18),quoterGas:gas.toString(),reason:'Read-only single-pool quoter simulation. Not a full wallet transaction simulation.'};}catch{return probe;}}));
 const best=probes.filter(p=>p.state==='quoted').sort((a,b)=>BigInt(a.outputRaw!)>BigInt(b.outputRaw!)?-1:1)[0]??null;
 const end=await rpc('eth_getBlockByNumber',[block,false]) as {hash?:string};if(end.hash!==header.hash)throw new Error('Block changed during inspection');const now=Date.now();
 const blockers=['Owner authority and bounded onchain permissions are unverified.','Eligibility for this user and trading venue has not been established.','Allowance, full router/account simulation and complete execution fees remain unverified.','Daily budget and portfolio concentration must be rechecked before execution.'];if(BigInt(String(balance))<raw)blockers.unshift('Insufficient observed USDG tokens.');if(!best)blockers.unshift('No quote from the four inspected direct pools. Other pools or venues may exist.');
 return {id:crypto.randomUUID(),chainId:CHAIN.id,address:address.toLowerCase(),symbol,token:asset.contract,settlement:VENUE.settlement,input:amount,inputRaw:raw.toString(),settlementDecimals:decimals,block,blockHash:header.hash!,blockAt:new Date(Number(BigInt(header.timestamp!))*1000).toISOString(),observedAt:new Date(now).toISOString(),expiresAt:new Date(Math.min(now+30000,Number(BigInt(header.timestamp!))*1000+30000)).toISOString(),balanceRaw:String(balance),slippageBps,probes,best,minimumOutputRaw:best?((BigInt(best.outputRaw!)*BigInt(10000-slippageBps))/10000n).toString():null,executionEnabled:false,coverage:'Four direct USDG/stock Uniswap v4 pool keys: fixed fees 100/500/3000/10000, tick spacing 1/10/60/200, zero hooks. No RFQ, multihop or hooked-pool discovery. USDG amount is not a guaranteed USD valuation.',blockers};
}
