import {tradeIntent} from './trade-intent.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {evaluateExecution,sessionPermissionReport,type ExecutionEvidence} from './execution-guard.ts';import type {RouteEvidence} from './chain-route.ts';
const now=Date.parse('2026-09-26T12:00:00Z'),future=new Date(now+20000).toISOString(),address='0x'+'a'.repeat(40);
function fixture():ExecutionEvidence{const e={route:{id:'route',chainId:4663,address,observedAt:new Date(now).toISOString(),blockAt:new Date(now).toISOString(),expiresAt:future,best:{state:'quoted',poolId:'0x'+'b'.repeat(64)},settlement:'0x'+'1'.repeat(40),token:'0x'+'2'.repeat(40),inputRaw:'1000000',minimumOutputRaw:'1',blockHash:'0x'+'c'.repeat(64)} as RouteEvidence,owner:address,mandateVersion:2,observedMandateVersion:2,paused:false,ownershipVerified:true,eligibilityVerified:true,permission:{installed:true,expiresAt:future,revoked:false,tokenCaps:true,recipients:true,outputTokens:true,calldata:true,revocationTested:true,implementationVerified:true},fundsVerified:true,dailyReserved:true,concentrationVerified:true,simulation:{success:true,account:address,routeId:'route',blockHash:'0x'+'c'.repeat(64),intentDigest:''},fees:{complete:true,withinCap:true},intentDigest:'',approval:{mode:'approval',intentDigest:'',routeId:'route',mandateVersion:2,expiresAt:future}} as ExecutionEvidence;e.intentDigest=tradeIntent(e.route,e.mandateVersion).digest;e.simulation.intentDigest=e.intentDigest;e.approval.intentDigest=e.intentDigest;return e;}
test('passing internal preflight never activates or submits an execution',()=>{const result=evaluateExecution(fixture(),now);assert.equal(result.checksPassed,true);assert.equal(result.executionEnabled,false);});
test('pause, account changes, mandate changes, stale block and stale quote block action',()=>{for(const mutate of [(e:ExecutionEvidence)=>e.paused=true,(e:ExecutionEvidence)=>e.owner='0x'+'b'.repeat(40),(e:ExecutionEvidence)=>e.observedMandateVersion=3,(e:ExecutionEvidence)=>e.route.expiresAt=new Date(now-1).toISOString(),(e:ExecutionEvidence)=>e.route.blockAt=new Date(now-31000).toISOString(),(e:ExecutionEvidence)=>e.route.observedAt=new Date(now+1).toISOString(),(e:ExecutionEvidence)=>e.route.chainId=1]){const e=fixture();mutate(e);assert.equal(evaluateExecution(e,now).checksPassed,false);}});
test('broad router access cannot pass missing recipient, output, calldata, revocation or implementation guards',()=>{for(const field of ['tokenCaps','recipients','outputTokens','calldata','revocationTested','implementationVerified','installed'] as const){const e=fixture();e.permission[field]=false;e.approval.mode='automatic';assert.equal(evaluateExecution(e,now).checksPassed,false);}const revoked=fixture();revoked.permission.revoked=true;assert.equal(evaluateExecution(revoked,now).checksPassed,false);assert.equal(sessionPermissionReport().grantable,false);});
test('insufficient accounting, ineligible owner, mismatched simulation, fees and exact approval fail closed',()=>{for(const mutate of [(e:ExecutionEvidence)=>e.eligibilityVerified=false,(e:ExecutionEvidence)=>e.ownershipVerified=false,(e:ExecutionEvidence)=>e.fundsVerified=false,(e:ExecutionEvidence)=>e.dailyReserved=false,(e:ExecutionEvidence)=>e.concentrationVerified=false,(e:ExecutionEvidence)=>e.simulation.routeId='other',(e:ExecutionEvidence)=>e.simulation.blockHash='other',(e:ExecutionEvidence)=>e.fees.complete=false,(e:ExecutionEvidence)=>e.fees.withinCap=false,(e:ExecutionEvidence)=>e.approval.routeId='other',(e:ExecutionEvidence)=>e.approval.mandateVersion=1]){const e=fixture();mutate(e);assert.equal(evaluateExecution(e,now).checksPassed,false);}});

test('mutating any bounded trade detail cannot reuse simulation or approval evidence',()=>{for(const mutate of [(e:ExecutionEvidence)=>e.route.inputRaw='2000000',(e:ExecutionEvidence)=>e.route.token='0x'+'3'.repeat(40),(e:ExecutionEvidence)=>e.route.minimumOutputRaw='2',(e:ExecutionEvidence)=>e.route.best!.poolId='0x'+'d'.repeat(64),(e:ExecutionEvidence)=>e.route.expiresAt=new Date(now+10000).toISOString(),(e:ExecutionEvidence)=>e.simulation.intentDigest='0x'+'e'.repeat(64),(e:ExecutionEvidence)=>e.approval.intentDigest='0x'+'e'.repeat(64)]){const e=fixture();mutate(e);assert.equal(evaluateExecution(e,now).checksPassed,false);}});
test('malformed or unbounded raw amounts fail closed without throwing',()=>{for(const value of ['garbage','-1','0','1e3','9'.repeat(79)]){const e=fixture();e.route.minimumOutputRaw=value;assert.equal(evaluateExecution(e,now).checksPassed,false);assert.equal(evaluateExecution(e,now).executionEnabled,false);}});
