import {tradeIntent} from './trade-intent.ts';
import type {RouteEvidence} from './chain-route.ts';
// Application checks cannot substitute for onchain session restrictions.
export type ExecutionEvidence={route:RouteEvidence;intentDigest:string;owner:string;mandateVersion:number;observedMandateVersion:number;paused:boolean;ownershipVerified:boolean;eligibilityVerified:boolean;permission:{installed:boolean;expiresAt:string;revoked:boolean;tokenCaps:boolean;recipients:boolean;outputTokens:boolean;calldata:boolean;revocationTested:boolean;implementationVerified:boolean};fundsVerified:boolean;dailyReserved:boolean;concentrationVerified:boolean;simulation:{success:boolean;account:string;routeId:string;blockHash:string;intentDigest:string};fees:{complete:boolean;withinCap:boolean};approval:{mode:'approval'|'automatic';intentDigest:string|null;routeId:string|null;mandateVersion:number|null;expiresAt:string|null}};
export function evaluateExecution(e:ExecutionEvidence,now=Date.now()){
 const reasons:string[]=[];const require=(pass:boolean,why:string)=>{if(!pass)reasons.push(why);};
 let digest:string|null=null;try{digest=tradeIntent(e.route,e.mandateVersion).digest;}catch{/* Invalid intents are blocked, never prepared. */}
 require(!!digest&&digest===e.intentDigest,'Exact bounded intent is missing or changed.');
 const fresh=(t:string|null,window:number)=>!!t&&Number.isFinite(Date.parse(t))&&Date.parse(t)>=now&&Date.parse(t)<=now+window;
 require(!e.paused,'Execution is paused.');require(e.owner.toLowerCase()===e.route.address,'Owner and route account differ.');require(e.route.chainId===4663,'Wrong execution network.');
 require(e.mandateVersion>0&&e.mandateVersion===e.observedMandateVersion,'Saved boundaries changed or are absent.');require(e.ownershipVerified,'Wallet ownership is unverified.');require(e.eligibilityVerified,'Eligibility is unverified.');
 require(fresh(e.route.expiresAt,30000)&&Date.parse(e.route.observedAt)<=now&&now-Date.parse(e.route.observedAt)<=30000&&Date.parse(e.route.blockAt)<=now&&now-Date.parse(e.route.blockAt)<=30000,'Route evidence expired or has an invalid timestamp.');require(!!digest&&!!e.route.best&&e.route.best.state==='quoted','No bounded output quote.');
 const p=e.permission;require(p.installed&&!p.revoked&&fresh(p.expiresAt,86400000),'Permission missing, expired or revoked.');require(p.tokenCaps&&p.recipients&&p.outputTokens&&p.calldata&&p.revocationTested&&p.implementationVerified,'Onchain permission coverage is incomplete. Router access alone is insufficient.');
 require(e.fundsVerified&&e.dailyReserved&&e.concentrationVerified,'Funds, reserved daily budget or concentration evidence is missing.');require(e.simulation.success&&e.simulation.account.toLowerCase()===e.owner.toLowerCase()&&e.simulation.routeId===e.route.id&&e.simulation.blockHash===e.route.blockHash&&!!digest&&e.simulation.intentDigest===digest,'Full account simulation is missing or mismatched.');require(e.fees.complete&&e.fees.withinCap,'Complete fees within the cap are required.');
 require(e.approval.mode==='automatic'||(e.approval.intentDigest===digest&&!!digest&&e.approval.routeId===e.route.id&&e.approval.mandateVersion===e.mandateVersion&&fresh(e.approval.expiresAt,30000)),'Exact owner approval is missing or expired.');
 return {checksPassed:reasons.length===0,reasons,executionEnabled:false as const,why:'Preflight only. No signer or submission adapter is connected.'};
}
export function sessionPermissionReport(){return {provider:'Alchemy Wallet APIs',grantable:false,executionEnabled:false,documented:['ERC-20 cumulative transfer/approval cap','Gas limit','Contract/function allowlist','Session expiry'],missing:['Router command argument restrictions','Exact output-token restriction','Exact recipient restriction','Tested deployed enforcement and revocation'],why:'Do not generate a root grant or broad router grant. The documented API permissions do not establish all required invariants.'};}
