import test from 'node:test';import assert from 'node:assert/strict';import {newPracticeSession,transitionPractice,type PracticeSession} from './practice-session.ts';import type {Strategy} from './strategy.ts';import type {Mandate} from './decision.ts';
const now=Date.UTC(2026,8,28,12);const m={version:1,allowedSymbols:['AAPL'],maxOrderCents:200,maxDailyBuyCents:200,maxPositionBps:2000,requireApproval:true} as Mandate;
const strategy:Strategy={version:1,kind:'scheduled',direction:'Buy $1 daily',symbol:'AAPL',amountCents:100,reserveCents:2000,intervalHours:24,thresholdCents:18000,targetBps:1000,driftBps:200,maxMovementBps:500,mode:'approval'};
const act=(s:PracticeSession,action:Parameters<typeof transitionPractice>[2],at=now,mandate=m)=>transitionPractice(s,mandate,action,at);
function ready(mode:Strategy['mode']='approval'){let s=act(newPracticeSession(now),{action:'confirm',strategy:{...strategy,mode}});return act(s,{action:'authorize'});}
test('exact approval changes 1000 to 999 once and cannot be replayed',()=>{let s=act(ready(),{action:'run'});assert.equal(s.account.cashCents,100000);const id=s.receipts[0].id;s=act(s,{action:'approve',id},now+1000);assert.equal(s.account.cashCents,99900);assert.equal(s.account.holdingsCents.AAPL,100);assert.throws(()=>act(s,{action:'approve',id}));});
test('price, clock, replacement, revocation and expiry invalidate pending approval',()=>{for(const command of [{action:'price',symbol:'AAPL',priceCents:18100},{action:'advance'},{action:'confirm',strategy},{action:'revoke'}] as const){const before=act(ready(),{action:'run'});const id=before.receipts[0].id;const next=act(before,command);assert.throws(()=>act(next,{action:'approve',id}));assert.equal(next.account.cashCents,100000);}const expired=act(act(ready(),{action:'run'}),{action:'refresh'},now+60000);assert.equal(expired.receipts[0].outcome,'held');assert.equal(expired.account.cashCents,100000);});
test('automatic background runs respect interval and daily reset',()=>{let s=ready('automatic');s=act(s,{action:'start'});s=act(s,{action:'background',enabled:true});s=transitionPractice(s,m,{action:'run'},now,'background');assert.equal(s.account.cashCents,99900);s=act(s,{action:'run'},now+900000);assert.equal(s.receipts[0].outcome,'held');assert.equal(s.account.cashCents,99900);s=act(s,{action:'run'},now+86400000);assert.equal(s.account.grant,false);assert.equal(s.account.cashCents,99900);s=act(s,{action:'authorize'},now+86400000);s=act(s,{action:'run'},now+86400000+9000);assert.equal(s.account.cashCents,99800);assert.equal(s.account.spentCents,100);});
test('safeguard scenarios hold funds and reset requires revocation',()=>{for(const scenario of ['stale','cash','daily','concentration'] as const){let s=ready('automatic');s=act(s,{action:'scenario',scenario});const cash=s.account.cashCents;s=act(s,{action:'run'});assert.equal(s.receipts[0].outcome,'held');assert.equal(s.account.cashCents,cash);}assert.throws(()=>act(ready(),{action:'reset'}));const reset=act(act(ready(),{action:'revoke'}),{action:'reset'});assert.equal(reset.account.cashCents,100000);assert.equal(reset.account.grant,false);});
test('mandate changes revoke permission and stop background execution',()=>{let s=act(act(ready(),{action:'start'}),{action:'background',enabled:true});s=act(s,{action:'refresh'},now,{...m,version:2});assert.equal(s.background,false);assert.equal(s.running,false);assert.equal(s.account.grant,false);});
