export const CHAIN = { id:4663, hex:"0x1237", name:"Robinhood Chain", rpc:"https://rpc.mainnet.chain.robinhood.com/", explorer:"https://robinhoodchain.blockscout.com" };
export type ChainHolding = {symbol:string;contract:string;raw:string;decimals:number|null;quantity:string|null;status:string};
export type ChainObservation = {address:string;chainId:number;block:string;observedAt:string;eth:string;scanned:number;holdings:ChainHolding[];failures:number;source:string};
export function units(raw:string, decimals:number):string { if(!/^0x[0-9a-f]+$/i.test(raw)||!Number.isInteger(decimals)||decimals<0||decimals>36) throw new Error("Invalid token amount."); const n=BigInt(raw).toString().padStart(decimals+1,"0"); if(!decimals)return n;const fraction=n.slice(-decimals).replace(/0+$/,"");return n.slice(0,-decimals)+(fraction?"."+fraction:""); }
export function registry(body:unknown) { const assets=(body as {assets?:unknown[]})?.assets;if(!Array.isArray(assets)||!assets.length||assets.length>1000) throw new Error("Official asset registry unavailable.");
 const seen=new Set<string>(); const tokens: {symbol:string;contract:string;status:string}[]=[];
 for(const entry of assets){const a=entry as {tokenSymbol?:string;status?:string;deployments?:{chainId:number;contractAddress:string}[]};if(!a.tokenSymbol||!Array.isArray(a.deployments))throw new Error("Asset registry incomplete."); for(const d of a.deployments){if(d.chainId!==CHAIN.id)continue;if(!/^0x[0-9a-f]{40}$/i.test(d.contractAddress))throw new Error("Asset address invalid.");const key=d.contractAddress.toLowerCase();if(seen.has(key))continue;seen.add(key);tokens.push({symbol:a.tokenSymbol,contract:key,status:a.status??"Unknown"});}}
 if(!tokens.length||tokens.length>500)throw new Error("Supported asset coverage unavailable or exceeds scan limit.");return tokens; }
export async function readChain(address:string,fetcher:typeof fetch=fetch):Promise<ChainObservation>{
 if(!/^0x[0-9a-f]{40}$/i.test(address))throw new Error("Enter a valid EVM wallet address.");
 const request=async(url:string,init?:RequestInit)=>{const r=await fetcher(url,{...init,signal:AbortSignal.timeout(12000),cache:"no-store"});if(!r.ok)throw new Error("Robinhood data service unavailable. Try again later.");return r.json();};
 let id=0;const batch=async(calls:{method:string;params:unknown[]}[])=>{const payload=calls.map(c=>({...c,jsonrpc:"2.0",id:++id}));const body=await request(CHAIN.rpc,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}) as {id:number;result?:string;error?:unknown}[];if(!Array.isArray(body))throw new Error("Network response unavailable.");return payload.map(c=>body.find(r=>r.id===c.id));};
 const head=await batch([{method:"eth_chainId",params:[]},{method:"eth_blockNumber",params:[]}]);if(head[0]?.result!==CHAIN.hex||!/^0x[0-9a-f]+$/i.test(head[1]?.result??""))throw new Error("Network identity could not be verified.");const block=head[1]!.result!;
 const tokens=registry(await request("https://api.robinhood.com/rhj/assets"));const ethResult=await batch([{method:"eth_getBalance",params:[address,block]}]);if(!ethResult[0]?.result)throw new Error("Native balance unavailable.");
 const holdings:ChainHolding[]=[];let failures=0;
 for(let start=0;start<tokens.length;start+=25){const slice=tokens.slice(start,start+25);const values=await batch(slice.map(t=>({method:"eth_call",params:[{to:t.contract,data:"0x70a08231"+address.slice(2).toLowerCase().padStart(64,"0")},block]})));for(let i=0;i<slice.length;i++){const raw=values[i]?.result;if(!raw||!/^0x[0-9a-f]{64}$/i.test(raw)){failures++;continue;}if(BigInt(raw)>0n)holdings.push({...slice[i],raw,decimals:null,quantity:null});}}
 for(let start=0;start<holdings.length;start+=25){const slice=holdings.slice(start,start+25);const values=await batch(slice.map(t=>({method:"eth_call",params:[{to:t.contract,data:"0x313ce567"},block]})));for(let i=0;i<slice.length;i++){const raw=values[i]?.result;const n=raw&&/^0x[0-9a-f]{64}$/i.test(raw)?Number(BigInt(raw)):NaN;if(Number.isInteger(n)&&n>=0&&n<=36){slice[i].decimals=n;slice[i].quantity=units(slice[i].raw,n);}}}
 return {address:address.toLowerCase(),chainId:CHAIN.id,block,observedAt:new Date().toISOString(),eth:units(ethResult[0]!.result!,18),scanned:tokens.length,holdings,failures,source:"Robinhood official asset API + mainnet RPC"};
}
