import {keccak256,type Hex} from 'viem';import {CHAIN} from './robinhood-chain.ts';import {routerCandidate,validateRouterCandidate} from './router-candidate.ts';import type {RouteEvidence} from './chain-route.ts';import {compileRolesPolicy,approvedRouterCall,encodeRolesExecution,type RolesPolicy} from './roles-permission.ts';import {inspectRolesInstallation} from './roles-installation.ts';
export function rolesOperation(route:RouteEvidence,version:number,policy:RolesPolicy){const plan=compileRolesPolicy(policy),candidate=routerCandidate(route,version);const call=approvedRouterCall(policy,route.token as `0x${string}`,Math.floor(Date.parse(route.expiresAt)/1000));if(policy.account.toLowerCase()!==route.address.toLowerCase()||!validateRouterCandidate(route,version,call)||call.data!==candidate.data)throw Error('Route does not match the owner-scoped permission.');const envelope=encodeRolesExecution(policy.module,plan.roleKey,call);return {...envelope,from:policy.session,intentDigest:candidate.intentDigest,policyHash:plan.policyHash,envelopeHash:keccak256(envelope.data),submissionEnabled:false as const};}
// Read-only eth_call and gas estimation through the complete Roles -> Safe -> router path.
// No state overrides, fabricated balances, signature or transaction submission.
export async function simulateRolesOperation(route:RouteEvidence,version:number,policy:RolesPolicy,creationTx:Hex,fetcher:typeof fetch=fetch,now=Date.now()){
 const result={state:'blocked' as 'blocked'|'simulated',intentDigest:null as string|null,policyHash:null as string|null,envelopeHash:null as string|null,estimatedGas:null as string|null,blockHash:route.blockHash,completeFees:false as const,executionEnabled:false as const,why:'Full permission/account simulation is unavailable or inconsistent. No transaction was sent.'};let serial=0;
 async function rpc(method:string,params:unknown[]){const id=++serial,r=await fetcher(CHAIN.rpc,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id,method,params}),signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok)throw Error('RPC unavailable');const b=await r.json() as {id:number;error?:unknown;result?:unknown};if(b.id!==id||b.error||!Object.hasOwn(b,'result'))throw Error('RPC unavailable');return b.result;}
 try{if(!Number.isFinite(now)||Date.parse(route.expiresAt)<=now||now-Date.parse(route.observedAt)>30000||now<Date.parse(route.observedAt))throw Error('Expired route');const operation=rolesOperation(route,version,policy);result.intentDigest=operation.intentDigest;result.policyHash=operation.policyHash;result.envelopeHash=operation.envelopeHash;
 const installed=await inspectRolesInstallation(policy,creationTx,fetcher,route.block as Hex);if(installed.state!=='verified_policy_state'||installed.blockHash!==route.blockHash||BigInt(installed.dailyRemainingCalls??'0')<1n||BigInt(installed.totalRemainingCalls??'0')<1n)throw Error('Permission missing or exhausted');
 const call={from:operation.from,to:operation.to,data:operation.data,value:operation.value};const raw=await rpc('eth_call',[call,route.block]);if(typeof raw!=='string'||raw.toLowerCase()!=='0x'+'0'.repeat(63)+'1')throw Error('Invalid call response');const gas=await rpc('eth_estimateGas',[call,route.block]);if(typeof gas!=='string'||!/^0x[0-9a-f]+$/i.test(gas)||BigInt(gas)===0n)throw Error('No gas evidence');
 const canonical=await rpc('eth_getBlockByNumber',[route.block,false]) as {hash:string};if(canonical?.hash!==route.blockHash)throw Error('Block changed');result.estimatedGas=BigInt(gas).toString();result.state='simulated';result.why='Complete Roles/Safe/router call and execution gas estimate passed at the recorded canonical block. Fresh ownership, eligibility, dollar accounting, all fees and an approved signer remain separate gates.';
 }catch{/* No unchecked fallback or balance override. */}return result;
}
