import test from 'node:test';import assert from 'node:assert/strict';import {encodeAbiParameters} from 'viem';import {routePrerequisites} from './route-prerequisites.ts';import type {RouteEvidence} from './chain-route.ts';
const address='0x'+'1'.repeat(40),hash='0x'+'a'.repeat(64);
const route={id:'r',address,chainId:4663,settlement:'0x'+'2'.repeat(40),token:'0x'+'3'.repeat(40),symbol:'AAPL',inputRaw:'1000000',balanceRaw:'2000000',minimumOutputRaw:'123',block:'0x12',blockHash:hash,expiresAt:new Date(Date.now()+25000).toISOString(),best:{poolId:hash}} as RouteEvidence;
const mandate={version:1,allowedSymbols:['AAPL'],maxOrderCents:100,maxDailyBuyCents:100,maxPositionBps:2000,requireApproval:true as const};
function mock(unknown=false,reorg=false){return (async(_url,init)=>{const p=JSON.parse(String(init?.body));assert.ok(['eth_call','eth_getCode','eth_getBlockByNumber'].includes(p.method));if(p.method==='eth_getBlockByNumber')return Response.json({id:p.id,result:{hash:reorg?'bad':hash}});if(p.method==='eth_getCode')return Response.json({id:p.id,result:'0x6000'});if(unknown)return Response.json({id:p.id,error:{code:-1}});const data=p.params[0].data;return Response.json({id:p.id,result:data.startsWith('0xdd62ed3e')?encodeAbiParameters([{type:'uint256'}],[1000000n]):encodeAbiParameters([{type:'uint160'},{type:'uint48'},{type:'uint48'}],[1000000n,Math.floor(Date.now()/1000)+60,0])});}) as typeof fetch;}
test('reads existing allowances and binds recipient, pool, mandate and exact input without granting permission',async()=>{const p=await routePrerequisites(route,mandate,mock());assert.equal(p?.tokenAllowanceRaw,'1000000');assert.equal(p?.intent.recipient,address);assert.equal(p?.executionEnabled,false);assert.equal(p?.calldataPrepared,false);assert.equal(p?.checks.find(c=>c.name==='Permit2 allowance to router')?.state,'pass');const changed=await routePrerequisites({...route,inputRaw:'1000001'},mandate,mock());assert.notEqual(changed?.intent.digest,p?.intent.digest);assert.equal(changed?.checks.find(c=>c.name==='Token allowance to Permit2')?.state,'fail');});
test('unknown allowances are pending, changed canonical blocks abort, expired quotes fail',async()=>{const p=await routePrerequisites({...route,expiresAt:new Date(0).toISOString()},mandate,mock(true));assert.equal(p?.tokenAllowanceRaw,null);assert.equal(p?.checks.find(c=>c.name==='Token allowance to Permit2')?.state,'pending');assert.equal(p?.checks.find(c=>c.name==='Quote freshness')?.state,'fail');await assert.rejects(routePrerequisites(route,mandate,mock(false,true)),/block could not/);});

test('router identity reads distinguish canonical manager, mismatch and unavailable evidence',async()=>{for(const manager of ['0x8366a39cc670b4001a1121b8f6a443a643e40951','0x'+'9'.repeat(40),null]){const base=mock();const f=(async(url,init)=>{const q=JSON.parse(String(init?.body));if(q.method==='eth_call'&&q.params[0].data==='0xdc4c90d3')return Response.json(manager?{id:q.id,result:encodeAbiParameters([{type:'address'}],[manager as `0x${string}`])}:{id:q.id,error:{code:-1}});return base(url,init);}) as typeof fetch;const p=await routePrerequisites(route,mandate,f);assert.equal(p?.checks.find(c=>c.name==='Router pool manager')?.state,manager===null?'pending':manager.startsWith('0x8366')?'pass':'fail');assert.equal(p?.executionEnabled,false);}});
