import {keccak256,type Hex} from 'viem';import {CHAIN} from './robinhood-chain.ts';import {EXECUTION_CONTRACTS} from './autonomy.ts';
export type WalletProfile={address:string;block:string|null;blockHash:string|null;observedAt:string;kind:'undelegated_eoa'|'delegated'|'contract'|'unavailable';codeHash:string|null;delegate:string|null;delegateCodeHash:string|null;documentedDelegate:boolean;ownershipVerified:false;permissionVerified:false;executionEnabled:false;why:string};
// EIP-7702's indicator is 0xef0100 || address. Detecting it is not permission verification.
export async function walletProfile(address:string,fetcher:typeof fetch=fetch,atBlock?:string):Promise<WalletProfile>{
 if(!/^0x[0-9a-f]{40}$/i.test(address)||atBlock&&!/^0x[0-9a-f]+$/i.test(atBlock))throw Error('Invalid wallet inspection');
 const result:WalletProfile={address:address.toLowerCase(),block:null,blockHash:null,observedAt:new Date().toISOString(),kind:'unavailable',codeHash:null,delegate:null,delegateCodeHash:null,documentedDelegate:false,ownershipVerified:false,permissionVerified:false,executionEnabled:false,why:'Canonical wallet-code evidence is unavailable. No control or permission conclusion was made.'};
 let serial=0;async function rpc(method:string,params:unknown[]){const id=++serial,r=await fetcher(CHAIN.rpc,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id,method,params}),signal:AbortSignal.timeout(10000),cache:'no-store'});if(!r.ok)throw Error('RPC unavailable');const b=await r.json() as {id:number;result?:unknown;error?:unknown};if(b.id!==id||b.error||!Object.hasOwn(b,'result'))throw Error('RPC unavailable');return b.result;}
 try{if(await rpc('eth_chainId',[])!==CHAIN.hex)throw Error('Wrong chain');const block=atBlock??await rpc('eth_blockNumber',[]);if(typeof block!=='string'||!/^0x[0-9a-f]+$/i.test(block))throw Error('Invalid block');const header=await rpc('eth_getBlockByNumber',[block,false]) as {hash:string;number:string};if(!header||header.number!==block||!/^0x[0-9a-f]{64}$/i.test(header.hash))throw Error('Missing header');
 const code=await rpc('eth_getCode',[address,block]);if(typeof code!=='string'||!/^0x(?:[0-9a-f]{2})*$/i.test(code))throw Error('Invalid code');result.block=block;result.blockHash=header.hash;result.codeHash=keccak256(code as Hex);
 if(code==='0x'){result.kind='undelegated_eoa';result.why='No account bytecode or delegation indicator at this block. Ownership and spending authority are still unverified.';}
 else if(/^0xef0100[0-9a-f]{40}$/i.test(code)){result.kind='delegated';result.delegate='0x'+code.slice(8).toLowerCase();const delegatedCode=await rpc('eth_getCode',[result.delegate,block]);if(typeof delegatedCode!=='string'||!/^0x(?:[0-9a-f]{2})+$/i.test(delegatedCode))throw Error('Delegation target unavailable');result.delegateCodeHash=keccak256(delegatedCode as Hex);result.documentedDelegate=result.delegate===EXECUTION_CONTRACTS.delegate.toLowerCase();result.why='An EIP-7702 delegation indicator and target bytecode were observed. Installed session limits, signer permissions and revocation remain unverified.';}
 else{result.kind='contract';result.why='Contract account code observed. Its execution and validation implementation has not been verified.';}
 const end=await rpc('eth_getBlockByNumber',[block,false]) as {hash:string};if(end?.hash!==header.hash)throw Error('Block changed');
 }catch{result.kind='unavailable';result.codeHash=null;result.delegateCodeHash=null;result.documentedDelegate=false;result.why='Canonical wallet-code evidence is unavailable or inconsistent. No control or permission conclusion was made.';}
 result.observedAt=new Date().toISOString();return result;
}
