import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {checkAlerts,createAlert,listAlerts,removeAlert} from '@/db/price-alerts';
import {readBoundedText} from '@/lib/strategy-ai-server';
import {z} from 'zod';
const headers={'Cache-Control':'no-store'};
const createInput=z.object({symbol:z.string().trim().regex(/^[A-Z][A-Z0-9.]{0,7}$/),direction:z.enum(['above','below']),priceCents:z.number().int().positive().max(100000000)}).strict();
const removeInput=z.object({id:z.string().min(1).max(64)}).strict();
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Alert storage is unavailable.'},{status:503,headers});try{const check=new URL(request.url).searchParams.get('check')==='1';const result=check?await checkAlerts(env.DB,user.userId):{alerts:await listAlerts(env.DB,user.userId),triggered:[],checked:0};return Response.json({alerts:result.alerts,triggered:result.triggered,checked:result.checked,notice:'Alerts compare read-only indicative bid quotes when you check them. No order is ever placed.'},{headers});}catch{return Response.json({error:'Alerts are temporarily unavailable.'},{status:503,headers});}}
export async function PUT(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Alert storage is unavailable.'},{status:503,headers});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin.'},{status:403,headers});let body;try{body=createInput.parse(JSON.parse(await readBoundedText(request,2000)));}catch{return Response.json({error:'Check the alert symbol, direction and price.'},{status:400,headers});}try{return Response.json({alert:await createAlert(env.DB,user.userId,body)},{headers});}catch(e){return Response.json({error:e instanceof Error?e.message:'Could not save the alert.'},{status:400,headers});}}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in first.'},{status:401,headers});if(!env.DB)return Response.json({error:'Alert storage is unavailable.'},{status:503,headers});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin.'},{status:403,headers});let body;try{body=removeInput.parse(JSON.parse(await readBoundedText(request,2000)));}catch{return Response.json({error:'Invalid alert.'},{status:400,headers});}try{const removed=await removeAlert(env.DB,user.userId,body.id);return Response.json({removed},{headers});}catch{return Response.json({error:'Could not remove the alert.'},{status:503,headers});}}
