import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {reserveAttempt,getAttempt,beginAttempt,recordSubmission,recordUnknown,cancelReservation,settleAttempt,recoverInterruptedAttempt,type AttemptPlan} from './execution-attempts.ts';
import type {RouterCandidate} from '../lib/router-candidate.ts';
function fixture(){
 const sql=new DatabaseSync(':memory:');
 sql.exec('CREATE TABLE autonomy_spends(owner_ref TEXT,address TEXT,execution_day TEXT,intent_id TEXT,amount_cents INTEGER,state TEXT,PRIMARY KEY(owner_ref,address,intent_id));');
 sql.exec(readFileSync(new URL('../drizzle/0010_flimsy_paibok.sql',import.meta.url),'utf8'));
 const db={prepare(query:string){let values:(string|number|null)[]=[];const statement={bind(...args:(string|number|null)[]){values=args;return statement;},async run(){return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}};},async first(){return sql.prepare(query).get(...values)??null;}};return statement;},async batch(statements:{run:()=>Promise<unknown>}[]){sql.exec('BEGIN');try{const output=[];for(const s of statements)output.push(await s.run());sql.exec('COMMIT');return output;}catch(error){sql.exec('ROLLBACK');throw error;}}} as unknown as D1Database;
 return {db,sql};
}
const now=new Date('2026-09-27T12:00:00Z'),address='0x'+'a'.repeat(40),hash='0x'+'b'.repeat(64);
function plan(n:number,owner='alice',amount=60):AttemptPlan{const digest='0x'+n.toString(16).padStart(64,'0');return {owner,address,intentDigest:digest,mandateVersion:1,day:'2026-09-27',amountCents:amount,dailyCapCents:100,candidate:{from:address,intentDigest:digest} as RouterCandidate};}
test('real SQLite migration and atomic reservations reject duplicates and isolate owners',async()=>{const {db,sql}=fixture();try{const p=plan(1);assert.equal(await reserveAttempt(db,p,now),true);assert.equal(await reserveAttempt(db,p,now),false);assert.equal(await reserveAttempt(db,plan(2),now),false);assert.equal(await reserveAttempt(db,plan(3,'bob'),now),true);assert.equal(await getAttempt(db,'bob',p.intentDigest),null);assert.equal(await reserveAttempt(db,plan(4,'alice',40),now),true);}finally{sql.close();}});
test('attempt claim is one-time, mandate-bound and uncertain outcomes retain budget across days',async()=>{const {db,sql}=fixture();try{const p=plan(1);await reserveAttempt(db,p,now);assert.equal(await beginAttempt(db,'alice',p.intentDigest,2,now),false);assert.equal(await beginAttempt(db,'alice',p.intentDigest,1,now),true);assert.equal(await beginAttempt(db,'alice',p.intentDigest,1,now),false);assert.equal(await recoverInterruptedAttempt(db,'alice',p.intentDigest,now),true);assert.equal(await cancelReservation(db,'alice',p.intentDigest,now),false);assert.equal(await beginAttempt(db,'alice',p.intentDigest,1,now),false);const tomorrow=new Date('2026-09-28T12:00:00Z');assert.equal(await reserveAttempt(db,{...plan(2),day:'2026-09-28'},tomorrow),false);assert.equal(await recordSubmission(db,'alice',p.intentDigest,hash,now),true);assert.equal(await recordUnknown(db,'alice',p.intentDigest,now),true);assert.equal(await recordSubmission(db,'alice',p.intentDigest,'0x'+'c'.repeat(64),now),false);assert.equal((await getAttempt(db,'alice',p.intentDigest))?.transaction_hash,hash);}finally{sql.close();}});
test('only unattempted reservations release without final evidence; outer success is not a verified fill',async()=>{const {db,sql}=fixture();try{const p=plan(1);await reserveAttempt(db,p,now);assert.equal(await cancelReservation(db,'bob',p.intentDigest,now),false);assert.equal(await cancelReservation(db,'alice',p.intentDigest,now),true);const q=plan(2);await reserveAttempt(db,q,now);await beginAttempt(db,'alice',q.intentDigest,1,now);await recordSubmission(db,'alice',q.intentDigest,hash,now);const proof={hash,canonicalFinalized:true,outcome:'unknown' as const,intentDigest:q.intentDigest};assert.equal(await settleAttempt(db,'alice',q.intentDigest,proof,now),false);assert.equal(await settleAttempt(db,'alice',q.intentDigest,{...proof,outcome:'reverted',canonicalFinalized:false},now),false);assert.equal(await settleAttempt(db,'alice',q.intentDigest,{...proof,outcome:'reverted',intentDigest:p.intentDigest},now),false);assert.equal(await settleAttempt(db,'alice',q.intentDigest,{...proof,outcome:'reverted'},now),true);assert.equal((await getAttempt(db,'alice',q.intentDigest))?.state,'reverted');assert.equal(sql.prepare('SELECT state FROM autonomy_spends WHERE intent_id=?').get(q.intentDigest)?.state,'released');}finally{sql.close();}});
test('a transaction hash cannot settle another intent and confirmed current-day spend still counts',async()=>{const {db,sql}=fixture();try{const p=plan(1);await reserveAttempt(db,p,now);await beginAttempt(db,'alice',p.intentDigest,1,now);await recordSubmission(db,'alice',p.intentDigest,hash,now);assert.equal(await settleAttempt(db,'alice',p.intentDigest,{hash,canonicalFinalized:true,outcome:'verified_fill',intentDigest:p.intentDigest},now),true);assert.equal(await reserveAttempt(db,plan(2,'alice',41),now),false);const q=plan(3,'bob');await reserveAttempt(db,q,now);await beginAttempt(db,'bob',q.intentDigest,1,now);assert.equal(await recordSubmission(db,'bob',q.intentDigest,hash.toUpperCase().replace('0X','0x'),now),false);assert.equal((await getAttempt(db,'bob',q.intentDigest))?.state,'attempting');assert.equal(await settleAttempt(db,'alice',p.intentDigest,{hash,canonicalFinalized:true,outcome:'reverted',intentDigest:p.intentDigest},now),false);}finally{sql.close();}});
