import type { Metadata } from "next";
import { ArrowRight, ArrowUpRight, BookOpen, Braces, Check, CircleDot, FileText, LockKeyhole, ShieldCheck } from "lucide-react";
import { BrandMark, BrandName } from "@/components/brand";
import { RouteLink } from "@/components/route-transition";
import { capabilityStatus, guideChapters, guideRevision } from "@/lib/product-guide";
import "./guide.css";

export const metadata: Metadata = {
  title: "How Stock Steward works — technical guide",
  description: "The current product state, mandate, broker evidence, decision checks, and receipt lifecycle of Stock Steward.",
};

export default function Guide() {
  return <div className="guide">
    <header className="guide-header"><RouteLink href="/" className="guide-brand" aria-label="Stock Steward home"><BrandMark /><BrandName /></RouteLink><div className="guide-header-right"><span>Product guide</span><RouteLink href="/workspace">Open workspace <ArrowUpRight size={15} /></RouteLink></div></header>
    <div className="guide-layout">
      <aside className="guide-sidebar"><div className="guide-sidebar-inner"><span className="guide-overline">DOCUMENTATION / V1</span><h2>How it works</h2><nav aria-label="Guide chapters">{guideChapters.map((chapter) => <a key={chapter.id} href={`#${chapter.id}`}><span>{chapter.number}</span>{chapter.title}</a>)}</nav><div className="guide-sidebar-foot"><CircleDot size={15} /> Reviewed {guideRevision}</div></div></aside>
      <main className="guide-main">
        <div className="guide-hero"><span className="guide-overline"><BookOpen size={14} /> STOCK STEWARD / TECHNICAL GUIDE</span><h1>A reason behind<br /><em>every decision.</em></h1><p>This guide describes the product as it exists today, the rules in its decision engine, and the work required before it can handle real brokerage funds.</p><div className="guide-hero-meta"><span><CircleDot size={14} /> Broker disconnected</span><span><LockKeyhole size={14} /> No live orders</span><span>Updated {guideRevision}</span></div></div>

        <section className="guide-chapter" id="overview"><ChapterHead number="01" title="The model" lead="Stock Steward is meant to act within boundaries you define, then leave enough evidence for you to understand an action or a hold." /><div className="guide-flow"><div><EyeMark number="01" /><strong>Observe</strong><p>Read a current, authenticated account snapshot.</p></div><div><EyeMark number="02" /><strong>Check</strong><p>Evaluate each configured rule against a proposed buy.</p></div><div><EyeMark number="03" /><strong>Authorize</strong><p>Ask the account owner before an eligible order is sent.</p></div><div><EyeMark number="04" /><strong>Reconcile</strong><p>Record the broker-confirmed outcome under the same receipt.</p></div></div><p>The product treats a hold as a meaningful result. If a check fails, the proposal stays held and its receipt explains the observed value, the limit, and what would have to change. A passed check is only a proposal awaiting approval, never a fill.</p><div className="guide-note"><ShieldCheck size={18} /><span>The 10-second sequence on the landing page is illustrative. It is not an account event or a live market observation.</span></div></section>

        <section className="guide-chapter" id="status"><ChapterHead number="02" title="What is live today" lead="The workspace stores owner records locally. Alpaca connection and guarded order code exist, but this checkout has no registered app credentials or connected account." /><div className="guide-status-table">{capabilityStatus.map((item) => <div key={item.name}><strong>{item.name}</strong><span>{item.state}</span><p>{item.detail}</p></div>)}</div><p>Sign-in identifies the workspace owner and saved mandates are stored in D1. Once an Alpaca OAuth app is configured, an eligible account owner can review the data permission on a dedicated connection page before consenting to a read-only connection. A later trading upgrade has its own permission review and required Alpaca disclosure. A proposed buy then triggers a fresh broker read and creates a receipt only if all required evidence is complete. No live account has validated this path yet, and no order submission or automatic action is enabled.</p></section>

        <section className="guide-chapter" id="mandate"><ChapterHead number="03" title="Your mandate" lead="A mandate is the versioned rule set the decision engine would cite when it evaluates a proposed buy." /><div className="guide-spec"><div><span>Approved symbols</span><p>Only stocks you list may be considered. An empty list approves no stock purchases.</p></div><div><span>Maximum single buy</span><p>A proposed order cannot exceed this dollar amount.</p></div><div><span>Maximum daily buys</span><p>Filled buys today and open buy orders count together with the proposed amount.</p></div><div><span>Maximum position share</span><p>The projected stock position cannot exceed this share of portfolio value.</p></div><div><span>Action preference</span><p>Ask for approval is the default. Automatic within limits can be saved as a future preference, but is inactive and grants no trading authority.</p></div></div><p>The workspace shows a live preview of the draft rule sentence, position ceiling, and action preference as fields change. Reset draft restores the last saved values without creating a new version. Saving increments the mandate version in the signed-in owner’s D1 ledger. The server validates the limits and rejects stale versions from another session. Approval remains required by the decision and order-event code regardless of the stored preference. Local preview sign-in is a development identity; it is not a brokerage identity. A changed mandate invalidates an unapproved order plan.</p></section>

        <section className="guide-chapter" id="evidence"><ChapterHead number="04" title="Broker evidence" lead="A decision needs a trustworthy snapshot. The Alpaca reader builds one server-side from OAuth-authorized responses." /><p>The evaluator expects an account reference, stock symbol, quote and its own timestamp, current position value, portfolio value, buying power, today’s executed buys, open buy orders across the account, open buys for this stock, tradability, and an observation time. It rejects a snapshot more than 60 seconds away from evaluation time, a quote older than 30 seconds, or incomplete values.</p><div className="guide-code"><div><Braces size={16} /> Expected input fields</div><code>symbol · quote + quote time · position value · portfolio value<br />buying power · executed buys today · open buys today<br />open buys for symbol · tradable · observed at · account reference</code></div><p>The server-side check loads the owner’s mandate and encrypted Alpaca connection, reads the broker account, positions, asset, open orders, recent IEX quote, and UTC-day fills, checks the account and symbol, then stores a receipt. The decision clock starts after the read completes. Cash caps buying power so margin is not used. Stale quotes, incomplete history, and open buys that cannot be valued safely stop the check without saving a decision. The browser submits only a symbol and proposed dollar amount, never supposed account figures. The <code>source</code> field identifies the adapter; authenticated requests and account binding establish provenance.</p></section>

        <section className="guide-chapter" id="checks"><ChapterHead number="05" title="Decision checks" lead="The evaluator returns every passed and failed check, so a decision has an inspectable basis." /><ol className="guide-checks"><li><strong>Approved symbol</strong><span>The proposed ticker is in the mandate’s allowlist.</span></li><li><strong>Broker tradability</strong><span>The broker currently permits trading that stock.</span></li><li><strong>Order size</strong><span>The proposed amount is at or below the single-buy maximum.</span></li><li><strong>Buying power</strong><span>Available buying power covers the proposed amount.</span></li><li><strong>Daily buy limit</strong><span>Filled buys, open buys, and the proposal stay within the day’s cap.</span></li><li><strong>Position concentration</strong><span>Current position value, open buys, and the proposal stay within the configured portfolio share.</span></li></ol><p>The concentration check uses the current portfolio value as its denominator: buying with account cash changes allocation but does not add new account equity. The projected share is rounded up to basis points so the limit is not understated. Failed checks create a held receipt; passing all checks creates an approval request.</p></section>

        <section className="guide-chapter" id="receipts"><ChapterHead number="06" title="Decision receipts" lead="A receipt is the record that connects a proposal to its evidence, rule results, and later outcome." /><div className="guide-receipt"><div><span>INTENT</span><strong>Proposal</strong><p>Symbol and proposed dollar amount.</p></div><div><span>CONTEXT</span><strong>Evidence</strong><p>Timestamped broker snapshot and mandate version.</p></div><div><span>REASON</span><strong>Checks</strong><p>Observed value, limit, pass or fail, and an explanation for each rule.</p></div><div><span>RESULT</span><strong>Status</strong><p>Held or checks passed; no order is sent today.</p></div></div><p>The evaluator also produces a short reason and conditions needed to change a hold. The D1 ledger stores versioned mandates, receipts, and append-only order events under an owner reference. After an authorized Alpaca read, the workspace can create and display a real decision receipt with broker figures and every check. No account has completed this path yet. Example numbers appear only in the labeled landing-page walkthrough.</p></section>

        <section className="guide-chapter" id="orders"><ChapterHead number="07" title="Order lifecycle" lead="Owner choice, authorization, submission, and broker outcome remain distinct records." /><div className="guide-event-chain"><div><Check size={16} /><strong>Owner choice</strong><span>Decline now, or review an exact order when approval becomes available</span></div><div><ArrowRight size={15} /><strong>Submitted</strong><span>Broker order ID recorded only after authorization</span></div><div><FileText size={16} /><strong>Filled or rejected</strong><span>Broker-confirmed outcome</span></div></div><p>A checks-passed receipt shows the exact proposed amount and stock. The owner can decline it once; that event is persisted and no order is sent. A connected owner can recheck any earlier proposal against fresh broker data, producing a new receipt while preserving the old one. A held or declined decision cannot become an order. The model requires account-owner authorization before submission, and a broker order ID before a fill or rejection. Approval and submission are disabled in this checkout; manual reconciliation is coded but has not been tested with a live order. The guarded route requires a passing recent receipt, current mandate, same broker account, and exact owner acknowledgement.</p><p>A fresh passing check may show a read-only Alpaca order plan: stock, exact dollar notional, account, day market-order type, and expiry no later than 30 seconds after the underlying quote. The server refuses to plan from a changed mandate or account, failed checks, an earlier decline, stale evidence, or an unsupported amount. The plan alone does not authorize or send an order. With separate trading consent and an explicit deployment switch, one owner-approved POST may be sent. An account-level gate blocks a second Stock Steward order until the first has a terminal broker outcome; the next decision must use a later broker observation. Immediately before the attempt, Steward reads the broker again, reruns every limit, and stores those figures and rule results in the event trail. A changed or stale snapshot aborts the submission. An uncertain response is looked up by client order ID rather than retried. Partial fills and terminal outcomes come from the broker response or later lookup. A manual trail refresh checks pending orders among the 50 visible receipts using broker GET requests only; it also marks older approvals that never reached a durable submission attempt as unsent. The refresh runs only when the owner requests it, so it is not background monitoring.</p></section>

        <section className="guide-chapter" id="roadmap"><ChapterHead number="08" title="Before real money" lead="Real-fund use needs a supported connection, durable records, deliberate authorization, and broker-confirmed reconciliation." /><div className="guide-roadmap"><div><span>01</span><strong>Alpaca Connect first</strong><p>Register an OAuth app, obtain owner consent, then read positions, quotes, buying power, tradability, open orders, and daily fills from authenticated responses. Confirm account and funding eligibility for each launch country.</p></div><div><span>02</span><strong>Account-bound storage</strong><p>Bind broker consent and receipts to the signed-in account owner with clear version history and access controls.</p></div><div><span>03</span><strong>Approval and execution</strong><p>Present an exact order for owner approval, submit only after that action and app approval, then store the broker’s order ID.</p></div><div><span>04</span><strong>Monitoring and reconciliation</strong><p>Handle stale quotes, rejected orders, partial fills, restarts, and repeated events without inventing outcomes.</p></div></div><p>Stock Steward is intended for eligible users across multiple countries, initially for US-listed stocks with USD purchase limits. Alpaca Connect is the first planned broker path, and the broker boundary permits a replacement if necessary. <a href="https://docs.alpaca.markets/us/docs/about-connect-api" target="_blank" rel="noreferrer">Alpaca Connect documents international OAuth users</a>. Live trading for other users needs separate Connect app approval. <a href="https://alpaca.markets/support/countries-alpaca-is-available" target="_blank" rel="noreferrer">Country support must be confirmed</a> before enabling a connection in a market. Live orders remain disabled until an eligible account owner can test the full path with real broker responses. Automatic action is only a saved preference today; it would require separate activation and tested controls after an approval based live path works.</p></section>

        <section className="guide-chapter guide-last" id="glossary"><ChapterHead number="09" title="Glossary" lead="A few terms used throughout the workspace and code." /><dl className="guide-glossary"><div><dt>Mandate</dt><dd>Your saved set of allowed symbols and purchase limits.</dd></div><div><dt>Proposal</dt><dd>A suggested buy before authorization or submission.</dd></div><div><dt>Hold</dt><dd>A proposal blocked by one or more checks; no order is sent.</dd></div><div><dt>Receipt</dt><dd>The inspectable record of evidence, rules, reason, and any later broker events.</dd></div><div><dt>Reconciliation</dt><dd>Matching a submitted order to a broker-confirmed fill or rejection.</dd></div></dl><div className="guide-end"><span>End of guide · Reviewed {guideRevision}</span><RouteLink href="/workspace">Go to workspace <ArrowRight size={16} /></RouteLink></div></section>
      </main>
    </div>
  </div>;
}

function ChapterHead({ number, title, lead }: { number: string; title: string; lead: string }) {
  return <div className="guide-chapter-head"><span>CHAPTER {number}</span><h2>{title}</h2><p>{lead}</p></div>;
}

function EyeMark({ number }: { number: string }) { return <span className="guide-flow-number">{number}</span>; }
