'use client';
import {useEffect,useState} from 'react';
import {goalGuidance,goalProgress,validateGoal,type GoalPlan,type SavedGoal} from '@/lib/goal-plan';
function readResponse(value:unknown):{goal:SavedGoal|null;error:string}{
 if(!value||typeof value!=='object')throw Error('Could not read the server response. Please try again.');
 const data=value as Record<string,unknown>;
 const error=typeof data.error==='string'?data.error:'Could not load or save your plan.';
 if(data.goal===null)return {goal:null,error};
 if(!data.goal||typeof data.goal!=='object'){if(data.error)return {goal:null,error};throw Error(error);}
 const goal=data.goal as Record<string,unknown>;
 if(!Number.isSafeInteger(goal.revision)||Number(goal.revision)<1||typeof goal.updatedAt!=='string'||!Number.isFinite(Date.parse(goal.updatedAt)))throw Error('Could not read your saved plan. Please reload it.');
 return {goal:{revision:Number(goal.revision),updatedAt:goal.updatedAt,plan:validateGoal(goal.plan)},error};
}
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const cents=(value:string)=>/^\d+(\.\d{1,2})?$/.test(value.trim())?Math.round(Number(value)*100):NaN;
export default function GoalPanel({onLimits,onPractice}:{onLimits:()=>void;onPractice:()=>void}){
 const [saved,setSaved]=useState<SavedGoal|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<GoalPlan|null>(null);
 const [name,setName]=useState(''),[target,setTarget]=useState(''),[current,setCurrent]=useState('0'),[monthly,setMonthly]=useState(''),[months,setMonths]=useState('12'),[comfort,setComfort]=useState<GoalPlan['comfort']>('cautious');
 function useSaved(goal:SavedGoal|null){setSaved(goal);if(goal){setName(goal.plan.name);setTarget(String(goal.plan.targetCents/100));setCurrent(String(goal.plan.currentCents/100));setMonthly(String(goal.plan.monthlyCents/100));setMonths(String(goal.plan.months));setComfort(goal.plan.comfort);}setReview(null);}
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/workspace/goal');const data=readResponse(await r.json());if(!r.ok)throw Error(data.error);useSaved(data.goal);setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'Could not load your plan.');}finally{setBusy(false);}}
 useEffect(()=>{let active=true;fetch('/api/workspace/goal').then(async r=>{const data=readResponse(await r.json());if(!r.ok)throw Error(data.error);if(active){useSaved(data.goal);setLoaded(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 const draft:GoalPlan={name:name.trim(),targetCents:cents(target),currentCents:cents(current),monthlyCents:cents(monthly),months:Number(months),comfort,startedAt:saved?.plan.startedAt??new Date().toISOString()};
 const valid=loaded&&draft.name.length>0&&draft.name.length<=80&&[draft.targetCents,draft.currentCents,draft.monthlyCents].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000000000)&&draft.targetCents>0&&Number.isInteger(draft.months)&&draft.months>=1&&draft.months<=600;
 const changed=!saved||(['name','targetCents','currentCents','monthlyCents','months','comfort'] as const).some(key=>draft[key]!==saved.plan[key]);
 const result=review?goalProgress(review):null,progress=saved?goalProgress(saved.plan):null;
 async function save(){if(!review||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/workspace/goal',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:saved?.revision??0,plan:review})});const data=readResponse(await r.json());if(!r.ok)throw Error(data.error);useSaved(data.goal);}catch(e){setError(e instanceof Error?e.message:'Could not save your plan.');}finally{setBusy(false);}}
 const preview=valid?goalProgress(draft):null;
 return <section className="ws-goal"><header className="goal-heading"><div><span className="ws-label">MY PLAN</span><h1>A goal worth building toward.</h1><p>Give your savings a destination. See what your monthly contributions can do.</p></div><span className="goal-badge">Contributions only · USD</span></header>
 {error&&<p className="ws-error" role="alert">{error} <button onClick={load} disabled={busy}>Reload saved plan</button></p>}
 {!loaded&&!error&&<p role="status">Loading your saved plan…</p>}
 {saved&&progress&&<section className="goal-summary" aria-label="Saved goal progress"><div className="goal-summary-main"><div className="goal-summary-top"><span className="ws-label">YOUR SAVED GOAL</span><span className="goal-badge">Saved · v{saved.revision}</span></div><h2>{saved.plan.name}</h2><div className="goal-amount"><strong>{money(saved.plan.currentCents)}</strong><span>of {money(saved.plan.targetCents)}</span></div><progress max="100" value={progress.percent} aria-label="Recorded goal progress"/><div className="goal-progress-caption"><span>{progress.percent}% recorded</span><span>{money(progress.gapCents)} to go</span></div></div><div className="goal-summary-facts"><div><span>Monthly contribution</span><strong>{money(saved.plan.monthlyCents)}</strong></div><div><span>Time remaining</span><strong>{progress.remainingMonths} <small>months</small></strong></div><div><span>Contribution projection</span><strong>{money(progress.projectedCents)}</strong></div></div><footer>Manually recorded savings · separate from Practice <span>Updated {new Date(saved.updatedAt).toLocaleDateString()}</span></footer></section>}
 <div className="goal-layout"><form className="goal-editor" onSubmit={e=>{e.preventDefault();if(valid&&changed)setReview(draft);}} onChange={()=>setReview(null)}><div className="goal-section-title"><span className="ws-label">01 / THE DETAILS</span><h2>Shape your plan</h2><p>Adjust your destination and pace.</p></div><fieldset disabled={!loaded||busy}><div className="ws-goal-fields">
 <label>What are you saving for?<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="For example, a home deposit"/></label>
 <label>Target amount · USD<input required inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)} placeholder="5000"/></label>
 <label>Amount saved so far · USD<input required inputMode="decimal" value={current} onChange={e=>setCurrent(e.target.value)}/><small>Update this yourself as your savings change.</small></label>
 <label>Monthly contribution · USD<input required inputMode="decimal" value={monthly} onChange={e=>setMonthly(e.target.value)} placeholder="100"/></label>
 <label>Timeframe · months<input required type="number" min="1" max="600" value={months} onChange={e=>setMonths(e.target.value)}/><small>{saved?'Measured from the original plan start date.':'Starts when you save this plan.'}</small></label>
 <label>How do price changes feel to you?<select value={comfort} onChange={e=>setComfort(e.target.value as GoalPlan['comfort'])}><option value="cautious">Cautious — losing value worries me</option><option value="balanced">Some ups and downs feel manageable</option><option value="comfortable">Comfortable with larger ups and downs</option></select><small>A preference for future planning guidance. This does not change any trade limits.</small></label></div>
 <div className="goal-form-footer"><span>{saved&&!changed?'All changes saved.':'Review before saving.'}</span><button className="ws-action-primary" disabled={!valid||!changed||busy||!!review}>Review my plan <span aria-hidden="true">→</span></button></div></fieldset></form>
 <aside className="goal-preview" aria-label="Contribution preview"><span className="ws-label">02 / THE OUTLOOK</span><h2>Your numbers,<br/>in perspective.</h2><p>Based on your draft contributions.</p>{preview?<><div className="goal-projection"><span>By the end of your timeframe</span><strong>{money(preview.projectedCents)}</strong><small>{money(draft.currentCents)} now + {money(draft.monthlyCents)} × {preview.remainingMonths} months</small></div><div className="goal-outcome"><span className="goal-outcome-label">{preview.gapCents===0?'Target reached':preview.remainingMonths===0?'Timeframe ended':preview.shortfallCents?'A gap to plan for':'Target covered'}</span><p>{preview.gapCents===0?'Your recorded savings already meet your target.':preview.remainingMonths===0?'Extend your timeframe or update your recorded savings.':preview.shortfallCents?`${money(preview.shortfallCents)} remains beyond your planned contributions.`:'Your planned contributions cover this target.'}</p>{preview.shortfallCents>0&&preview.remainingMonths>0&&<div className="goal-needed"><strong>{money(preview.requiredMonthlyCents!)}</strong><span>/ month to cover the target</span></div>}</div></>:<div className="goal-preview-empty"><span aria-hidden="true">↗</span><p>Add your goal and amounts to see the contribution outlook.</p></div>}
 {review&&result&&<div className="goal-confirm" aria-live="polite"><span className="ws-label">REVIEW BEFORE SAVING</span><p>Save <strong>{review.name}</strong> with these details?</p><button className="ws-action-primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save this plan'} <span aria-hidden="true">✓</span></button><button className="goal-text-button" disabled={busy} onClick={()=>setReview(null)}>Keep editing</button></div>}
 {saved&&!changed&&!review&&<div className="goal-saved" role="status"><span aria-hidden="true">✓</span><div><strong>Plan saved</strong><p>Your details are stored. Edit a field whenever you want to update them.</p></div><button className="ws-action-secondary" onClick={onLimits}>Next: set my limits →</button></div>}
 {saved&&progress&&(()=>{const guide=goalGuidance(saved.plan,progress);return <section className="goal-guidance" aria-label="Planning guidance"><span className="ws-label">YOUR COMFORT, APPLIED</span><h2>{guide.title}</h2><ul>{guide.points.map(point=><li key={point.text}><strong>{point.text}</strong><small>{point.detail}</small></li>)}</ul><small className="goal-guidance-note">General planning guidance only. It does not change your saved trade limits or select investments.</small></section>;})()}
 <p className="goal-disclaimer">No growth, losses, fees, taxes or inflation included. A contribution calculation, not a return forecast.</p></aside></div>
 <footer className="goal-next"><div><span className="ws-label">YOUR NEXT STEP</span><h2>Give your plan some boundaries.</h2><p>Set your limits, then test with fake funds. Saving a goal never authorizes trades.</p></div><div><button className="ws-action-secondary" onClick={onLimits}>Set my limits →</button><button className="goal-text-button" onClick={onPractice}>Open Practice →</button></div></footer></section>;
}
