'use client';
import {useEffect,useRef} from 'react';
export default function OverviewMotion({variant='overview',caption}:{variant?:'overview'|'mandate'|'trail';caption?:string}){
 const root=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{
  const view=root.current?.closest('.ws-view');if(!view||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const seen=new WeakSet<Element>(),animations=new Set<Animation>();let frame=0;let highlighted:HTMLElement|null=null;
  const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const el=entry.target as HTMLElement;observer.unobserve(el);el.style.opacity='';if(view.getAttribute('data-animate')==='false')continue;const animation=el.animate([{opacity:0,transform:'translateY(16px) scale(.99)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:280,easing:'cubic-bezier(.23,1,.32,1)'});animations.add(animation);animation.finished.then(()=>animations.delete(animation)).catch(()=>{});}},{threshold:.01,rootMargin:'0px 0px -20px 0px'});
  const scan=()=>{view.querySelectorAll<HTMLElement>('.ws-chain-panel,.ws-autonomy-panel,.ws-overview-grid>section,.ws-account-numbers>div,.ws-overview-trail,.ws-chain-holdings>details,.ws-editor,.ws-policy-preview,.ws-trail,.ws-receipt,.ws-field,.ws-execution-field').forEach(el=>{if(seen.has(el))return;seen.add(el);el.classList.add('ws-motion-card');if(el.getBoundingClientRect().top>window.innerHeight)el.style.opacity='0';observer.observe(el);});};scan();
  const changes=new MutationObserver(scan);changes.observe(view,{childList:true,subtree:true});
  const move=(event:Event)=>{const e=event as PointerEvent;if(e.pointerType!=='mouse')return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const el=(e.target as Element).closest<HTMLElement>('.ws-motion-card');if(highlighted!==el)highlighted?.removeAttribute('data-lit');highlighted=el;if(!el)return;const rect=el.getBoundingClientRect();el.style.setProperty('--pointer-x',((e.clientX-rect.left)/rect.width*100)+'%');el.style.setProperty('--pointer-y',((e.clientY-rect.top)/rect.height*100)+'%');el.setAttribute('data-lit','true');});};
  const keyboard=()=>view.setAttribute('data-input','keyboard');const pointer=()=>view.setAttribute('data-input','pointer');view.addEventListener('keydown',keyboard);view.addEventListener('pointerdown',pointer);const leave=()=>{highlighted?.removeAttribute('data-lit');};view.addEventListener('pointermove',move);view.addEventListener('pointerleave',leave);
  return()=>{view.removeEventListener('keydown',keyboard);view.removeEventListener('pointerdown',pointer);observer.disconnect();changes.disconnect();cancelAnimationFrame(frame);animations.forEach(a=>a.cancel());view.removeEventListener('pointermove',move);view.removeEventListener('pointerleave',leave);view.querySelectorAll<HTMLElement>('.ws-motion-card').forEach(el=>{el.style.opacity='';el.removeAttribute('data-lit');});};
 },[]);
 return <div ref={root} className={"ws-overview-orbit ws-motion-"+variant} aria-hidden="true"><div className="ws-orbit-halo"/><svg viewBox="0 0 240 160">{variant==='mandate'?<g><rect x="52" y="25" width="136" height="110" rx="24"/><path d="M74 54H166M74 80H166M74 106H166"/><circle className="ws-boundary-knob" cx="100" cy="54" r="6"/><circle className="ws-boundary-knob knob-two" cx="145" cy="80" r="6"/><circle className="ws-boundary-knob knob-three" cx="115" cy="106" r="6"/></g>:variant==='trail'?<g className="ws-ledger-art"><path d="M58 26V134"/><circle cx="58" cy="42" r="4"/><circle cx="58" cy="80" r="4"/><circle cx="58" cy="118" r="4"/>{[0,1,2].map(i=><g className="ws-ledger-sheet" style={{animationDelay:i*-.8+'s'}} key={i}><rect x="78" y={26+i*38} width="100" height="30" rx="8"/><path d={'M92 '+(38+i*38)+'H160M92 '+(46+i*38)+'H134'}/></g>)}</g>:<g><ellipse cx="120" cy="80" rx="96" ry="46"/><ellipse cx="120" cy="80" rx="66" ry="66"/><path d="M24 80H216M120 14V146"/><g className="ws-orbit-traveler"><circle cx="120" cy="14" r="5"/></g><circle className="ws-orbit-heart" cx="120" cy="80" r="14"/><circle cx="120" cy="80" r="5"/></g>}</svg><span>{caption??"OBSERVE · CHECK · EXPLAIN"}</span></div>;
}
