'use client';
import {useState,useEffect,useRef} from 'react';import {toHex} from 'viem';import type {OwnershipChallenge} from '@/lib/wallet-ownership';
type Provider={request:(p:{method:string;params?:unknown[]})=>Promise<unknown>};
export default function OwnershipPanel({address}:{address:string}){
 const [record,setRecord]=useState<OwnershipChallenge|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 useEffect(()=>{const ticket=++generation.current;setBusy(false);setError('');fetch('/api/workspace/ownership',{cache:'no-store'}).then(r=>r.json()).then(raw=>{const b=raw as {ownership?:OwnershipChallenge};if(ticket===generation.current)setRecord(b.ownership??null);}).catch(()=>{});return()=>{generation.current++;};},[address]);
 async function post(body:unknown){const r=await fetch('/api/workspace/ownership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json() as {ownership:OwnershipChallenge;error?:string};if(!r.ok)throw new Error(b.error??'Ownership check failed.');return b.ownership;}
 async function act(action:'challenge'|'sign'|'forget'){const ticket=++generation.current;setBusy(true);setError('');try{
  if(action==='challenge'){const c=await post({action,address});if(ticket===generation.current)setRecord(c);}
  else if(action==='forget'){await post({action});if(ticket===generation.current)setRecord(null);}
  else{if(!record||record.address!==address.toLowerCase()||record.verifiedAt)throw new Error('Request a fresh challenge first.');const p=(window as unknown as {ethereum?:Provider}).ethereum;if(!p)throw new Error('Use a browser with an EVM wallet. Never enter a private key.');const accounts=await p.request({method:'eth_requestAccounts'}) as string[];if(accounts[0]?.toLowerCase()!==address.toLowerCase())throw new Error('Choose the matching wallet account before signing.');const chain=await p.request({method:'eth_chainId'});if(BigInt(String(chain))!==4663n)throw new Error('Select Robinhood Chain in your wallet before verifying.');if(ticket!==generation.current)return;const signature=await p.request({method:'personal_sign',params:[toHex(record.message),address]});if(ticket!==generation.current)return;const verified=await post({action:'verify',challengeId:record.challengeId,signature});if(ticket===generation.current)setRecord(verified);}
 }catch(e){if(ticket===generation.current)setError(e instanceof Error?e.message:'Verification canceled or failed.');}finally{if(ticket===generation.current)setBusy(false);}}
 const matches=record?.address===address.toLowerCase();return <div className="ws-monitor"><span className="ws-label">WALLET CONTROL / NO SPENDING GRANT</span><h3>Prove control. Keep your keys.</h3><p>A short-lived message binds this wallet to your signed-in workspace. It does not approve tokens, install delegation or authorize trades. The signature is checked on the server; no private key is requested.</p><div className="ws-chain-tools"><button disabled={busy||!/^0x[0-9a-f]{40}$/i.test(address)} onClick={()=>act('challenge')}>Request ownership message</button>{record&&<button className="ws-recheck" disabled={busy} onClick={()=>act('forget')}>Forget verification</button>}</div>{matches&&record&&<div className="ws-chain-brief">{record.verifiedAt?<><strong>Control verified {new Date(record.verifiedAt).toLocaleString()}</strong><p>Historical {record.method} evidence. No session permission is installed; this does not guarantee future control.</p></>:<><details open><summary>Review exactly what your wallet will sign</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{record.message}</pre></details><button disabled={busy||Date.parse(record.expiresAt)<=Date.now()} onClick={()=>act('sign')}>{busy?'Verifying…':'Sign ownership message'}</button></>}</div>}{error&&<p className="ws-error" role="alert">{error}</p>}</div>;
}
