'use client';
import {useState,useEffect,useRef} from 'react';import {toHex} from 'viem';import type {OwnershipChallenge} from '@/lib/wallet-ownership';
import {matchingWallet,type WalletProvider} from '@/lib/browser-wallet';
export default function OwnershipPanel({address,provider}:{address:string;provider:WalletProvider|null}){
 const [record,setRecord]=useState<OwnershipChallenge|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now());const generation=useRef(0);
 useEffect(()=>{const ticket=++generation.current;setBusy(false);setError('');setRecord(null);fetch('/api/workspace/ownership',{cache:'no-store'}).then(r=>r.json()).then(raw=>{const b=raw as {ownership?:OwnershipChallenge};if(ticket===generation.current)setRecord(b.ownership??null);}).catch(()=>{});return()=>{generation.current++;};},[address,provider]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 async function post(body:unknown){const r=await fetch('/api/workspace/ownership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json() as {ownership:OwnershipChallenge;error?:string};if(!r.ok)throw new Error(b.error??'Ownership check failed.');return b.ownership;}
 async function act(action:'challenge'|'sign'|'forget'){const ticket=++generation.current;setBusy(true);setError('');try{
  if(action==='challenge'){const c=await post({action,address});if(ticket===generation.current)setRecord(c);}
  else if(action==='forget'){await post({action});if(ticket===generation.current)setRecord(null);}
  else{if(!record||record.address!==address.toLowerCase()||record.verifiedAt)throw new Error('Request a fresh challenge first.');const p=provider;if(!p)throw Error('Connect the matching wallet above before signing. Watching an address cannot prove ownership.');if(Date.parse(record.expiresAt)<=Date.now())throw Error('This message expired. Request a new ownership message.');await matchingWallet(p,address);if(ticket!==generation.current)return;const signature=await p.request({method:'personal_sign',params:[toHex(record.message),address]});if(ticket!==generation.current)return;await matchingWallet(p,address);if(ticket!==generation.current)return;const verified=await post({action:'verify',challengeId:record.challengeId,signature});if(ticket===generation.current)setRecord(verified);}
 }catch(e){if(ticket===generation.current)setError(e instanceof Error?e.message:'Verification canceled or failed.');}finally{if(ticket===generation.current)setBusy(false);}}
 const matches=record?.address===address.toLowerCase();return <div className="ws-monitor"><span className="ws-label">WALLET CONTROL / NO SPENDING GRANT</span><h3>Prove control. Keep your keys.</h3><p>A short-lived message binds this wallet to your signed-in workspace. It does not approve tokens, install delegation or authorize trades. The signature is checked on the server; no private key is requested.</p><div className="ws-chain-tools"><button className="ws-action-primary" disabled={busy||!/^0x[0-9a-f]{40}$/i.test(address)} onClick={()=>act('challenge')}>Review wallet verification</button>{record&&<button className="ws-recheck" disabled={busy} onClick={()=>act('forget')}>Forget verification</button>}</div>{matches&&record&&<div className="ws-chain-brief">{record.verifiedAt?<><strong>Wallet verified</strong><p>You proved control of this wallet on {new Date(record.verifiedAt).toLocaleString()}. No permission to spend was granted. Your connected account will be checked again before future authorization.</p></>:<><h4>Verify this wallet</h4><p>Sign a free message to link {address.slice(0,6)}…{address.slice(-4)} to your workspace. This authorizes no purchases and moves no funds.</p><details><summary>View the exact signing message</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{record.message}</pre></details><p>{Date.parse(record.expiresAt)<=now?"Message expired. Request a fresh message.":`Expires in ${Math.max(0,Math.ceil((Date.parse(record.expiresAt)-now)/1000))} seconds.`}</p>{!provider&&<p>Connect your wallet above to sign. Watch-only inspection needs no signature.</p>}<button className="ws-action-primary" disabled={busy||!provider||Date.parse(record.expiresAt)<=now} onClick={()=>act('sign')}>{busy?'Verifying…':'Open wallet & verify'}</button></>}</div>}{error&&<p className="ws-error" role="alert">{error}</p>}</div>;
}
