'use client';
import {useState,useRef,useEffect} from 'react';
import {ArrowUpRight} from 'lucide-react';
import type {AutonomyReceipt} from '@/lib/autonomy';
import type {RouteEvidence} from '@/lib/chain-route';
export function RouteDetails({route}:{route:RouteEvidence}){return <div className="ws-autonomy-result"><div className="ws-chain-brief"><strong>{route.best?'Live quoter evidence · execution blocked':'No quote from inspected pools'}</strong><p>{route.input} USDG → {route.symbol} · {route.best?.outputTokens??'Output unavailable'} raw stock tokens</p><small>Block {BigInt(route.block).toString()} · observed {new Date(route.observedAt).toLocaleString()} · quote expired after {new Date(route.expiresAt).toLocaleTimeString()}. Recheck before any future action.</small></div><p>{route.coverage}</p>{route.probes.map(p=><div className={`ws-receipt-check ws-partial-${p.state==='quoted'?'pass':'pending'}`} key={p.poolId}><b>{p.state.replaceAll('_',' ').toUpperCase()}</b><span><strong>Fee {p.fee/10000}% · spacing {p.tickSpacing}</strong><small>{p.reason}</small>{p.outputTokens&&<small>Quoted {p.outputTokens} tokens · quoter gas {p.quoterGas} (not full execution gas)</small>}</span></div>)}<details><summary>Inspect route and remaining gates</summary><p>Settlement {route.settlement} · input units {route.inputRaw}</p><p>Output {route.token} · minimum units {route.minimumOutputRaw??'Unverified'}</p><p>Block hash {route.blockHash}</p>{route.blockers.map(b=><p key={b}>{b}</p>)}</details></div>;}
export default function RoutePanel({address,onSaved}:{address:string;onSaved:(r:AutonomyReceipt)=>void}){
 const [symbol,setSymbol]=useState('AAPL'),[amount,setAmount]=useState('1'),[slippage,setSlippage]=useState('50'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[route,setRoute]=useState<RouteEvidence|null>(null);const generation=useRef(0);
 useEffect(()=>{generation.current++;setRoute(null);setBusy(false);return()=>{generation.current++;};},[address]);
 async function check(){const ticket=++generation.current;setBusy(true);setError('');setRoute(null);try{const response=await fetch('/api/workspace/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address,symbol,amount,slippageBps:Number(slippage)})});const data=await response.json() as {receipt:AutonomyReceipt;error?:string};if(!response.ok)throw new Error(data.error??'Route unavailable.');if(ticket===generation.current){setRoute(data.receipt.route!);onSaved(data.receipt);}}catch(e){if(ticket===generation.current)setError(e instanceof Error?e.message:'Route unavailable.');}finally{if(ticket===generation.current)setBusy(false);}}
 return <div className="ws-monitor"><span className="ws-label">LIVE ROUTE INVESTIGATION</span><h3>What can this amount actually reach?</h3><p>Read USDG settlement funds and simulate four direct Uniswap v4 pools against an official stock token. No approval, signature or transaction. A quote does not establish eligibility or safe autonomous authority.</p><div className="ws-route-fields"><label>Stock symbol<input value={symbol} disabled={busy} onChange={e=>{setSymbol(e.target.value.toUpperCase().trim());setRoute(null);}}/></label><label>USDG token amount<input value={amount} disabled={busy} inputMode="decimal" onChange={e=>{setAmount(e.target.value);setRoute(null);}}/></label><label>Output tolerance<select value={slippage} disabled={busy} onChange={e=>{setSlippage(e.target.value);setRoute(null);}}><option value="10">0.1%</option><option value="50">0.5%</option><option value="100">1%</option></select></label></div><button disabled={busy||!/^0x[0-9a-f]{40}$/i.test(address)} onClick={check}>{busy?'Reading pools…':'Inspect live route'} <ArrowUpRight size={16}/></button>{error&&<p className="ws-error" role="alert">{error}</p>}{route&&<RouteDetails route={route}/>}</div>;
}
