'use client';
import {useEffect,useRef,useState} from 'react';import {Sparkles,ArrowRight,Check} from 'lucide-react';import {reviewInterpretation} from '@/lib/strategy-interpretation';import type {Strategy} from '@/lib/strategy';
type Review=ReturnType<typeof reviewInterpretation>;
export default function StrategyAI({direction,base,onDraft}:{direction:string;base:Strategy;onDraft:(draft:Strategy)=>void}){
 const [available,setAvailable]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<Review|null>(null);const generation=useRef(0),controller=useRef<AbortController|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/workspace/strategy/interpret',{cache:'no-store',signal:c.signal}).then(r=>r.json()).then(b=>setAvailable((b as {available?:boolean}).available===true)).catch(()=>{if(!c.signal.aborted)setAvailable(false);});return()=>c.abort();},[]);
 useEffect(()=>{generation.current++;controller.current?.abort();setReview(null);setBusy(false);return()=>{generation.current++;controller.current?.abort();};},[direction,base]);
 async function interpret(){if(busy||!direction.trim())return;const ticket=++generation.current,c=new AbortController();controller.current=c;setBusy(true);setError('');setReview(null);try{
 const response=await fetch('/api/workspace/strategy/interpret',{method:'POST',headers:{'Content-Type':'application/json'},signal:c.signal,body:JSON.stringify({direction,base})});const body=await response.json() as {error?:string;review:{result:unknown}};if(ticket!==generation.current)return;if(!response.ok)throw Error(body.error??'AI interpretation is unavailable.');
 // Revalidate the response on the device before displaying or applying a draft.
 setReview(reviewInterpretation(body.review.result,direction,base));
 }catch(e){if(ticket===generation.current&&!c.signal.aborted)setError(e instanceof Error?e.message:'Could not interpret your direction. Try again or set the fields manually.');}finally{if(ticket===generation.current)setBusy(false);}}
 return <section className="ws-ai"><div className="ws-ai-heading"><Sparkles size={19}/><strong>Turn your direction into a draft</strong><span>AI ASSISTED</span></div><p>Describe your plan, then review the suggested rules. AI can misunderstand instructions. Your direction is sent to our AI provider when you click Interpret; no wallet keys or balances are sent.</p><div className="ws-action-row"><button className="ws-action-primary" disabled={busy||!direction.trim()||available!==true} onClick={interpret}><Sparkles size={16}/>{busy?'Interpreting your direction…':'Interpret my direction'}<ArrowRight size={16}/></button>{available===false&&<span>AI is not available yet. You can set your rules below.</span>}{available===null&&<span>Checking availability…</span>}</div>{error&&<p className="ws-error" role="alert">{error}</p>}
 {review&&<div className="ws-ai-review"><strong>{review.draft?'AI draft ready for your review':'A little more direction needed'}</strong><p>{review.draft?review.result.summary:'Clarify the details below using explicit amounts and numbers. No draft is ready yet.'}</p>{review.questions.map(q=><p key={q}>→ {q}</p>)}{review.unsupported.map(q=><p key={q}>Unsupported: {q}</p>)}{review.draft&&<><p>{review.draft.kind.replace('_',' ')} · {review.draft.kind==='portfolio'?review.draft.targets?.map(t=>t.symbol).join(', '):review.draft.symbol} · ${(review.draft.amountCents/100).toFixed(2)} maximum per trade · {review.draft.kind==='sell_threshold'||review.draft.kind==='sell_below'?'held shares required':`$${(review.draft.reserveCents/100).toFixed(2)} cash reserve`} · {review.draft.mode}.</p><button className="ws-action-primary" onClick={()=>{onDraft(review.draft!);setReview(null);}}><Check size={16}/>Use these draft rules <ArrowRight size={16}/></button></>}<small>No activation, permission or trade occurs here. Compare the fields with your direction, then review and confirm separately.</small></div>}
 </section>;
}
