'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Play,Pause,ShieldCheck} from 'lucide-react';
import {evaluateStrategy,practiceFill,validateStrategy,type Strategy,type PracticeEvidence,type StrategyResult,utcDay} from '@/lib/strategy';
import type {Mandate} from '@/lib/decision';
const money=(c:number)=>'$'+(c/100).toFixed(2);
const seed=():PracticeEvidence=>({now:Date.now(),quoteAt:Date.now(),cashCents:100000,holdingsCents:{},pricesCents:{AAPL:18000,META:50000,MSFT:42000},previousPricesCents:{AAPL:18000,META:50000,MSFT:42000},spentDay:utcDay(Date.now()),spentCents:0,lastFillAt:null,grant:false});
const initial:Strategy={version:1,kind:'scheduled',direction:'',symbol:'AAPL',amountCents:100,reserveCents:2000,intervalHours:24,thresholdCents:18000,targetBps:1000,driftBps:200,maxMovementBps:500,mode:'approval'};
type Receipt=StrategyResult&{id:string;outcome:'held'|'awaiting_approval'|'simulated_fill'|'declined';createdAt:string};
export default function StrategyPanel({mandate}:{mandate:Mandate}){
 const [mode,setMode]=useState<'practice'|'live'>('practice'),[draft,setDraft]=useState(initial),[review,setReview]=useState<Strategy|null>(null),[active,setActive]=useState<Strategy|null>(null),[running,setRunning]=useState(false),[account,setAccount]=useState(seed),[receipts,setReceipts]=useState<Receipt[]>([]),[error,setError]=useState('');
 const state=useRef({active,account,mandate,receipts});state.current={active,account,mandate,receipts};
 const [restored,setRestored]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem('steward-practice-strategy-v1');if(raw){const saved=validateStrategy(JSON.parse(raw) as Strategy);setDraft(saved);setActive(saved);}}catch{/* Invalid local drafts never activate permission. */}setRestored(true);},[]);
 useEffect(()=>{if(restored&&active)try{localStorage.setItem('steward-practice-strategy-v1',JSON.stringify(active));}catch{setError('Strategy could not be saved on this browser. Practice remains available for this session.');}},[active,restored]);
 // A changed mandate invalidates local practice permission and pending approvals.
 useEffect(()=>{setRunning(false);setAccount(e=>({...e,grant:false}));setReceipts(r=>r.map(x=>x.outcome==='awaiting_approval'?{...x,outcome:'declined',why:'Saved mandate changed. Re-authorize practice after reviewing the new limits.'}:x));},[mandate]);
 function run(){const {active:s,account:e,mandate:m,receipts:r}=state.current;if(!s)return;try{
  if(r.some(x=>x.outcome==='awaiting_approval'))return;
  const result=evaluateStrategy(s,m,e);let next=e;let outcome:Receipt['outcome']=result.status==='held'?'held':'awaiting_approval';
  if(result.status==='ready'){next=practiceFill(result,s,m,e);outcome='simulated_fill';}
  const receipt:Receipt={...result,id:crypto.randomUUID(),outcome,createdAt:new Date(e.now).toISOString()};
  state.current={...state.current,account:next,receipts:[receipt,...r].slice(0,50)};setAccount(next);setReceipts(state.current.receipts);setError('');
 }catch(e){setRunning(false);setError(e instanceof Error?e.message:'Practice check unavailable.');}}
 useEffect(()=>{if(!running||mode!=='practice')return;const timer=setInterval(()=>run(),8000);return()=>clearInterval(timer);},[running,mode]);
 function revoke(){setRunning(false);setAccount(e=>({...e,grant:false}));setReceipts(r=>r.map(x=>x.outcome==='awaiting_approval'?{...x,outcome:'declined',why:'Practice permission revoked; no simulated purchase made.'}:x));}
 function approve(receipt:Receipt){const {active:s,account:e,mandate:m,receipts:r}=state.current;if(!s||receipt.outcome!=='awaiting_approval'||!r.some(x=>x.id===receipt.id&&x.outcome==='awaiting_approval'))return;try{const next=practiceFill(receipt,s,m,e,true);state.current={...state.current,account:next,receipts:r.map(x=>x.id===receipt.id?{...x,outcome:'simulated_fill',why:'Exact practice purchase approved and simulated; no chain transaction.'}:x)};setAccount(next);setReceipts(state.current.receipts);setError('');}catch{setReceipts(r=>r.map(x=>x.id===receipt.id?{...x,outcome:'held',why:'Evidence or limits changed. Run a new check before approval.'}:x));setError('The approval expired because its evidence changed. Run a new check.');}}
 function update<K extends keyof Strategy>(key:K,value:Strategy[K]){setDraft(s=>({...s,[key]:value}));setReview(null);}
 function numeric(key:'amountCents'|'reserveCents'|'thresholdCents'|'targetBps'|'driftBps'|'maxMovementBps',value:string){const n=/^\d+(\.\d{0,2})?$/.test(value)?Math.round(Number(value)*100):NaN;update(key,n);}
 const field=(key:'amountCents'|'reserveCents'|'thresholdCents'|'targetBps'|'driftBps'|'maxMovementBps',label:string)=><label>{label}<input type="number" min="0" step="0.01" value={Number.isFinite(draft[key])?draft[key]/100:''} onChange={e=>numeric(key,e.target.value)}/></label>;
 function advance(hours:number){setAccount(e=>{const now=e.now+hours*3600000;return {...e,now,quoteAt:now};});}
 function changePrice(value:string){const price=Math.round(Number(value)*100);if(!Number.isSafeInteger(price)||price<1||price>100000000)return;const symbol=active?.symbol??draft.symbol;setAccount(e=>{const before=e.pricesCents[symbol];return {...e,pricesCents:{...e.pricesCents,[symbol]:price},previousPricesCents:{...e.previousPricesCents,[symbol]:before??price},holdingsCents:{...e.holdingsCents,[symbol]:before?Number(BigInt(e.holdingsCents[symbol]??0)*BigInt(price)/BigInt(before)):0},quoteAt:e.now};});}
 function download(){const blob=new Blob([JSON.stringify({schema:'stock-steward-practice-v1',notice:'Browser-local simulation with fixture prices. Not blockchain transactions or live financial evidence.',strategy:active,account,receipts},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='stock-steward-practice.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const symbols=[...new Set([...mandate.allowedSymbols,'AAPL','META','MSFT'])];
 return <section className="ws-strategy ws-check-panel">
  <div className="ws-account-head"><div><span className="ws-label">STRATEGY / REVIEW BEFORE ACTIVATION</span><h2>Your direction. Clear rules.</h2><p>Choose a supported strategy, review its exact rules, then practice the agent’s cycle before using real funds.</p></div><div className="ws-strategy-modes" aria-label="Funding mode"><button aria-pressed={mode==='practice'} onClick={()=>setMode('practice')}>Practice</button><button aria-pressed={mode==='live'} onClick={()=>{setMode('live');revoke();}}>Live</button></div></div>
  <div className="ws-chain-brief" role="status"><strong>{mode==='practice'?'Practice · simulated funds only':'Live · activation unavailable'}</strong><p>{mode==='practice'?'Same reviewed strategy and checks; balances and prices here are simulated. Purchases update a browser-local balance model, not testnet contracts. No wallet signature or gas is needed.':'Live wallet installation, owner authorization, fee review, accounting and signer integration are still required. Practice permission never carries over.'}</p></div>
  <div className="ws-strategy-types">{(['scheduled','threshold','allocation','accumulate'] as const).map(kind=><button key={kind} aria-pressed={draft.kind===kind} onClick={()=>update('kind',kind)}><strong>{{scheduled:'Scheduled buying',threshold:'Price threshold',allocation:'Target allocation',accumulate:'Cautious accumulation'}[kind]}</strong><small>{{scheduled:'Buy at a chosen interval',threshold:'Buy below your price ceiling',allocation:'Buy toward an allocation target',accumulate:'Space buys and limit price movement'}[kind]}</small></button>)}</div>
  <label className="ws-strategy-direction">Your direction / notes<textarea maxLength={1500} value={draft.direction} onChange={e=>update('direction',e.target.value)} placeholder="Describe what you want the agent to follow…"/><small>Notes are saved with the strategy. AI interpretation is not connected; only the structured rules below control practice. Unsupported requests such as selling or news-based trading will not execute.</small></label>
  <div className="ws-strategy-fields"><label>Approved stock<select value={draft.symbol} onChange={e=>update('symbol',e.target.value)}>{symbols.map(s=><option key={s}>{s}</option>)}</select></label>{field('amountCents','Purchase amount · USD')}{field('reserveCents','Keep cash available · USD')}
   {(draft.kind==='scheduled'||draft.kind==='accumulate')&&<label>Hours between completed buys<input type="number" min="1" max="8760" value={draft.intervalHours} onChange={e=>update('intervalHours',Number(e.target.value))}/></label>}
   {draft.kind==='threshold'&&field('thresholdCents','Buy at or below · USD per share')}
   {draft.kind==='allocation'&&<>{field('targetBps','Target allocation · %')}{field('driftBps','Trigger below target by · percentage points')}</>}
   {draft.kind==='accumulate'&&field('maxMovementBps','Maximum simulated price movement · %')}
   <label>Execution choice<select value={draft.mode} onChange={e=>update('mode',e.target.value as Strategy['mode'])}><option value="approval">Ask for each purchase</option><option value="automatic">Automatic within reviewed limits</option></select></label>
  </div><div className="ws-chain-tools"><button onClick={()=>{try{setReview(validateStrategy({...draft,version:(active?.version??0)+1}));setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid strategy.');}}}>Review strategy <ArrowRight size={16}/></button><span>Editing a draft does not change the active strategy.</span></div>
  {review&&<div className="ws-chain-brief"><strong>Confirm strategy v{review.version}</strong><p>{review.kind} · {money(review.amountCents)} of {review.symbol} · keep {money(review.reserveCents)} cash · {review.mode==='approval'?'ask before each purchase':'automatic practice execution'}.</p><p>{review.kind==='threshold'?`Only at or below ${money(review.thresholdCents)} per share.`:review.kind==='allocation'?`Target ${review.targetBps/100}%; trigger below ${(review.targetBps-review.driftBps)/100}%. Buys only; fixed purchases cannot overshoot the target.`:`Wait ${review.intervalHours} hours between buys.${review.kind==='accumulate'?` Pause when price movement exceeds ${review.maxMovementBps/100}%.`:''}`}</p><p>Saved mandate v{mandate.version||'—'} still governs allowed stocks, purchase size, daily budget and concentration. This confirms rules, not permission to spend.</p><button onClick={()=>{setActive(review);revoke();setReview(null);setError('');}}>Confirm reviewed strategy</button></div>}
  {error&&<p className="ws-error" role="alert">{error}</p>}
  {active&&<div className="ws-strategy-session"><span className="ws-label">{mode.toUpperCase()} / ACTIVE STRATEGY V{active.version}</span><h3>Observe. Check. Act or hold.</h3>
   {mode==='practice'?<><div className="ws-account-numbers"><div><span>Practice cash</span><strong>{money(account.cashCents)}</strong></div><div><span>Simulated holdings value</span><strong>{money(Object.values(account.holdingsCents).reduce((a,b)=>a+b,0))}</strong></div><div><span>Practice permission</span><strong>{account.grant?'Active':'Revoked'}</strong></div></div><p>Simulated clock: {new Date(account.now).toISOString()} · starts with $1,000 fake cash. Balances and receipts reset when this page reloads; the confirmed strategy stays on this browser.</p>
   <div className="ws-strategy-fields"><label>{active.symbol} fixture price · USD<input type="number" min="0.01" step="0.01" value={(account.pricesCents[active.symbol]??0)/100} onChange={e=>changePrice(e.target.value)}/></label></div>
   <div className="ws-chain-tools"><button disabled={!mandate.version||account.grant} onClick={()=>setAccount(e=>({...e,grant:true}))}><ShieldCheck size={16}/>Authorize practice only</button><button disabled={!account.grant} onClick={()=>setRunning(v=>!v)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?'Pause agent':'Start agent'}</button><button disabled={!account.grant} onClick={run}>Run one check</button><button onClick={revoke}>Revoke practice permission</button><button onClick={()=>advance(24)}>Advance test clock 24h</button><button onClick={()=>setAccount(e=>({...e,quoteAt:e.now}))}>Refresh fixture quote</button></div><p>{running?'Agent checks every eight seconds while this workspace is open.':'Agent is paused.'} Scheduled buys use the simulated clock. No unattended execution after closing the page. Live spending is not enabled.</p></>:<p>Reviewed strategy retained. Live activation is unavailable; no wallet request or real purchase will be made.</p>}
  </div>}
  <div className="ws-strategy-trail"><div className="ws-account-head"><h3>Practice decision trail</h3><button onClick={download} disabled={!receipts.length}>Download practice receipts</button></div>{!receipts.length&&<p>Authorize practice and run a check to see the agent’s reasoning here.</p>}{receipts.map(r=><details key={r.id}><summary><strong>{r.outcome.replaceAll('_',' ').toUpperCase()}</strong> · {r.symbol} · {money(r.amountCents)}<small>{r.createdAt}</small></summary><p>{r.why}</p><p>Practice · strategy v{r.strategyVersion} · mandate v{r.mandateVersion}. {r.outcome==='simulated_fill'?'Simulated balance updated. No transaction hash exists.':'No purchase made.'}</p>{r.checks.map(c=><div className="ws-receipt-check" key={c.name}><b>{c.passed?'PASS':'FAIL'}</b><span><strong>{c.name}</strong><small>{c.detail}</small></span></div>)}{r.outcome==='awaiting_approval'&&mode==='practice'&&<div className="ws-chain-tools"><button onClick={()=>approve(r)}>Approve exact practice purchase</button><button onClick={()=>setReceipts(old=>old.map(x=>x.id===r.id?{...x,outcome:'declined',why:'Owner declined the practice purchase.'}:x))}>Decline</button></div>}</details>)}</div>
 </section>;
}

