'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Play,Pause,ShieldCheck,Check,Clock3,Eye,SlidersHorizontal} from 'lucide-react';
import StrategyAI from './strategy-ai';
import PracticeBalance from './practice-balance';
import {validateStrategy,type Strategy} from '@/lib/strategy';
import {newPracticeSession,type PracticeReceipt as Receipt,type PracticeSession,type PracticeAction} from '@/lib/practice-session';
import type {Mandate} from '@/lib/decision';
const money=(c:number)=>'$'+(c/100).toFixed(2);
const initial:Strategy={version:1,kind:'scheduled',direction:'',symbol:'AAPL',amountCents:100,reserveCents:2000,intervalHours:24,thresholdCents:18000,targetBps:1000,driftBps:200,maxMovementBps:500,mode:'approval'};
export default function StrategyPanel({mandate}:{mandate:Mandate}){
 const [mode,setMode]=useState<'practice'|'live'>('practice'),[draft,setDraft]=useState(initial),[review,setReview]=useState<Strategy|null>(null),[session,setSession]=useState(newPracticeSession),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[backgroundAvailable,setBackgroundAvailable]=useState(false),[fixturePrice,setFixturePrice]=useState('180');
 const current=useRef(session),locked=useRef(false);current.current=session;const active=session.strategy,account=session.account,receipts=session.receipts,running=session.running;
 async function load(restoreDraft=false){try{const r=await fetch('/api/workspace/practice',{cache:'no-store'}),b=await r.json() as {session:PracticeSession;error:string;backgroundAvailable?:boolean};if(!r.ok)throw Error(b.error);const saved=b.session as PracticeSession;current.current=saved;setSession(saved);setBackgroundAvailable(b.backgroundAvailable===true);if(restoreDraft){if(saved.strategy)setDraft(saved.strategy);else try{const old=localStorage.getItem('steward-practice-strategy-v1');if(old){setDraft(validateStrategy(JSON.parse(old)));setError('Your previous browser strategy was restored as a draft. Review and confirm it to save this practice session.');}}catch{/* Invalid old browser rules do not become active. */}}setLoaded(true);}catch(e){setError(e instanceof Error?e.message:'Could not load saved practice.');}}
 useEffect(()=>{void load(true);},[mandate.version]);
 useEffect(()=>{setFixturePrice(String((account.pricesCents[active?.symbol??draft.symbol]??18000)/100));},[account.pricesCents,active?.symbol,draft.symbol]);
 async function command(action:PracticeAction){if(locked.current||!loaded)return false;locked.current=true;setBusy(true);setError('');try{const r=await fetch('/api/workspace/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:current.current.revision,command:action})}),b=await r.json() as {session:PracticeSession;error:string;backgroundAvailable?:boolean};if(!r.ok){await load();throw Error(b.error);}current.current=b.session;setSession(b.session);return true;}catch(e){setError(e instanceof Error?e.message:'Practice is unavailable. Your session was not changed.');return false;}finally{locked.current=false;setBusy(false);}}
 const commands=useRef(command);commands.current=command;
 useEffect(()=>{if(!running||mode!=='practice')return;const timer=setInterval(()=>{if(current.current.background)void load();else void commands.current({action:'run'});},8000);return()=>clearInterval(timer);},[running,mode]);
 useEffect(()=>{if(!loaded)return;const due=[session.permissionExpiresAt,...receipts.filter(r=>r.outcome==='awaiting_approval').map(r=>r.approvalExpiresAt)].filter((v):v is number=>v!==null&&v>Date.now());if(!due.length)return;const timer=setTimeout(()=>void load(),Math.min(...due)-Date.now()+100);return()=>clearTimeout(timer);},[session.permissionExpiresAt,receipts,loaded]);
 const run=()=>void command({action:'run'}),revoke=()=>void command({action:'revoke'}),approve=(receipt:Receipt)=>void command({action:'approve',id:receipt.id});
 function update<K extends keyof Strategy>(key:K,value:Strategy[K]){setDraft(s=>({...s,[key]:value}));setReview(null);}
 function numeric(key:'amountCents'|'reserveCents'|'thresholdCents'|'targetBps'|'driftBps'|'maxMovementBps',value:string){const n=/^\d+(\.\d{0,2})?$/.test(value)?Math.round(Number(value)*100):NaN;update(key,n);}
 const field=(key:'amountCents'|'reserveCents'|'thresholdCents'|'targetBps'|'driftBps'|'maxMovementBps',label:string)=><label>{label}<input type="number" min="0" step="0.01" value={Number.isFinite(draft[key])?draft[key]/100:''} onChange={e=>numeric(key,e.target.value)}/></label>;
 function changePrice(){const price=Math.round(Number(fixturePrice)*100);if(!Number.isSafeInteger(price)||price<1){setError('Enter a positive simulated price.');return;}void command({action:'price',symbol:active?.symbol??draft.symbol,priceCents:price});}
 function download(){const blob=new Blob([JSON.stringify({...session,notice:'Saved simulation with fake funds and fixture prices. No blockchain transactions or live financial evidence.'},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='stock-steward-practice.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const symbols=[...new Set([...mandate.allowedSymbols,'AAPL','META','MSFT',draft.symbol])];
 const pending=receipts.find(r=>r.outcome==='awaiting_approval');
 const decline=(id:string)=>void command({action:'decline',id});
 return <section className="ws-strategy ws-check-panel" aria-busy={busy}>
  <div className="ws-account-head"><div><span className="ws-label">STRATEGY / REVIEW BEFORE ACTIVATION</span><h2>Your direction. Clear rules.</h2><p>Choose a supported strategy, review its exact rules, then practice the agent’s cycle before using real funds.</p></div><div className="ws-strategy-modes" aria-label="Funding mode"><button aria-pressed={mode==='practice'} onClick={()=>setMode('practice')}>Practice</button><button aria-pressed={mode==='live'} onClick={()=>{setMode('live');revoke();}}>Live</button></div></div>
  <div className="ws-chain-brief" role="status"><strong>{mode==='practice'?'Practice · simulated funds only':'Live · activation unavailable'}</strong><p>{mode==='practice'?'Same reviewed strategy and checks; balances and prices here are simulated. Practice cash, holdings and receipts are saved in your signed-in workspace. Prices are fixtures, not live quotes or testnet contracts. No wallet signature or gas is needed.':'Live wallet installation, owner authorization, fee review, accounting and signer integration are still required. Practice permission never carries over.'}</p></div>
  <div className="ws-strategy-types">{(['scheduled','threshold','allocation','accumulate'] as const).map(kind=><button key={kind} aria-pressed={draft.kind===kind} onClick={()=>update('kind',kind)}><strong>{{scheduled:'Scheduled buying',threshold:'Price threshold',allocation:'Target allocation',accumulate:'Cautious accumulation'}[kind]}</strong><small>{{scheduled:'Buy at a chosen interval',threshold:'Buy below your price ceiling',allocation:'Buy toward an allocation target',accumulate:'Space buys and limit price movement'}[kind]}</small></button>)}</div>
  <label className="ws-strategy-direction">Tell Steward your direction<textarea maxLength={1500} value={draft.direction} onChange={e=>update('direction',e.target.value)} placeholder="Build AAPL toward 10%, buy $1 below 8%, keep $20 cash, and ask me before each purchase…"/><small>Write naturally, then use AI to suggest draft rules—or set the fields yourself. Only reviewed and confirmed rules run.</small></label>
  <StrategyAI direction={draft.direction} base={draft} onDraft={next=>{setDraft(next);setReview(null);setError('');}}/>
  <div className="ws-strategy-fields"><label>Approved stock<select value={draft.symbol} onChange={e=>update('symbol',e.target.value)}>{symbols.map(s=><option key={s}>{s}</option>)}</select></label>{field('amountCents','Purchase amount · USD')}{field('reserveCents','Keep cash available · USD')}
   {(draft.kind==='scheduled'||draft.kind==='accumulate')&&<label>Hours between completed buys<input type="number" min="1" max="8760" value={draft.intervalHours} onChange={e=>update('intervalHours',Number(e.target.value))}/></label>}
   {draft.kind==='threshold'&&field('thresholdCents','Buy at or below · USD per share')}
   {draft.kind==='allocation'&&<>{field('targetBps','Target allocation · %')}{field('driftBps','Trigger below target by · percentage points')}</>}
   {draft.kind==='accumulate'&&field('maxMovementBps','Maximum simulated price movement · %')}
   <label>Execution choice<select value={draft.mode} onChange={e=>update('mode',e.target.value as Strategy['mode'])}><option value="approval">Ask for each purchase</option><option value="automatic">Automatic within reviewed limits</option></select></label>
  </div><div className="ws-action-row"><button className="ws-action-primary" onClick={()=>{try{setReview(validateStrategy({...draft,version:(active?.version??0)+1}));setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid strategy.');}}}><SlidersHorizontal size={17}/>Review strategy <ArrowRight size={16}/></button><span>Editing a draft does not change the active strategy.</span></div>
  {review&&<div className="ws-review-card"><span className="ws-label">REVIEW / STRATEGY V{review.version}</span><h3>Your rules. Your call.</h3><p>{review.kind} · {money(review.amountCents)} of {review.symbol} · keep {money(review.reserveCents)} cash · {review.mode==='approval'?'ask before each purchase':'automatic practice execution'}.</p><p>{review.kind==='threshold'?`Only at or below ${money(review.thresholdCents)} per share.`:review.kind==='allocation'?`Target ${review.targetBps/100}%; trigger below ${(review.targetBps-review.driftBps)/100}%. Buys only; fixed purchases cannot overshoot the target.`:`Wait ${review.intervalHours} hours between buys.${review.kind==='accumulate'?` Pause when price movement exceeds ${review.maxMovementBps/100}%.`:''}`}</p><p>Saved mandate v{mandate.version||'—'} still governs allowed stocks, purchase size, daily budget and concentration. This confirms rules, not permission to spend.</p><button className="ws-action-primary" disabled={busy||!loaded} onClick={async()=>{if(await command({action:'confirm',strategy:review}))setReview(null);}}><Check size={17}/>Confirm these rules<ArrowRight size={16}/></button></div>}
  {!loaded&&<p role="status">Loading your saved practice session…</p>}{busy&&<p role="status">Saving practice changes…</p>}{error&&<p className="ws-error" role="alert">{error}</p>}
  {active&&<div className="ws-strategy-session"><span className="ws-label">{mode.toUpperCase()} / ACTIVE STRATEGY V{active.version}</span><h3>Observe. Check. Act or hold.</h3>
   {mode==='practice'?<><div className="ws-agent-cycle" aria-label="Agent state"><span><Eye size={16}/>Observe</span><span><SlidersHorizontal size={16}/>Check rules</span><span data-current={!!pending}>{pending?<Clock3 size={16}/>:<ShieldCheck size={16}/>} {pending?'Your approval needed':'Act or hold'}</span><span><Check size={16}/>Keep a receipt</span><i className={running?'is-running':''}/></div><div className="ws-account-numbers"><div><span>Practice cash</span><PracticeBalance cents={account.cashCents}/></div><div><span>Simulated holdings value</span><PracticeBalance cents={Object.values(account.holdingsCents).reduce((a,b)=>a+b,0)}/></div><div><span>Practice permission</span><strong>{account.grant?'Active':'Not authorized'}</strong>{account.grant&&session.permissionExpiresAt&&<small>Expires {new Date(session.permissionExpiresAt).toLocaleString()}</small>}</div></div>
   {pending&&<div className="ws-purchase-approval" role="status"><span className="ws-label"><Clock3 size={15}/> YOUR APPROVAL / PRACTICE ONLY</span><h3>Buy {money(pending.amountCents)} of {pending.symbol}?</h3><p>The checks passed. Your cash stays at {money(account.cashCents)} until you approve this exact simulated purchase.</p><div className="ws-action-row"><button className="ws-action-primary" disabled={busy} onClick={()=>approve(pending)}><Check size={17}/>Approve practice purchase</button><button className="ws-action-secondary" disabled={busy} onClick={()=>decline(pending.id)}>Decline</button></div><small>After approval: {money(account.cashCents-pending.amountCents)} practice cash. No real funds or wallet transaction.</small></div>}
   {!pending&&receipts[0]?.outcome==='simulated_fill'&&<p className="ws-fill-confirmation" role="status"><Check size={17}/>Practice purchase completed. Cash and holdings updated.</p>}
   <details className="ws-practice-tools"><summary>Simulated clock and price controls</summary><p>Clock: {new Date(account.now).toLocaleString()} · $1,000 starting fake cash. Balances and receipts survive reloads. Permission expires after 24 hours. Reset is available after revocation.</p>
   <div className="ws-strategy-fields"><label>{active.symbol} fixture price · USD<input type="number" min="0.01" step="0.01" value={fixturePrice} onChange={e=>setFixturePrice(e.target.value)}/></label></div>
   <div className="ws-action-row"><button className="ws-action-secondary" onClick={()=>void command({action:'advance'})}><Clock3 size={16}/>Advance clock 24h</button><button className="ws-action-secondary" onClick={()=>void command({action:'refresh_quote'})}>Refresh simulated quote</button><button className="ws-action-secondary" onClick={changePrice}>Apply simulated price</button></div>
   <div className="ws-practice-scenarios"><strong>Test a safeguard</strong><p>Each scenario pauses the agent and invalidates pending approvals. It changes fake balances only.</p>{([['healthy','Normal funds'],['stale','Stale quote'],['cash','No available cash'],['daily','Daily limit reached'],['concentration','Position too large']] as const).map(([scenario,label])=><button key={scenario} className="ws-action-secondary" disabled={busy} onClick={()=>void command({action:'scenario',scenario})}>{label}</button>)}</div><button className="ws-action-quiet" disabled={busy||account.grant||running} onClick={()=>void command({action:'reset'})}>Reset fake funds and receipts</button></details>
   <div className="ws-agent-controls">{account.grant?<span className="ws-authorized-status"><ShieldCheck size={17}/><Check size={15}/>Practice authorized</span>:<button className="ws-action-primary" disabled={!mandate.version||busy||!loaded} onClick={()=>void command({action:'authorize'})}><ShieldCheck size={17}/>Authorize practice</button>}<button className="ws-action-primary" disabled={!account.grant||busy} onClick={()=>void command({action:running?'pause':'start'})}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pause agent':'Start agent'}</button><button className="ws-action-secondary" disabled={!account.grant||!!pending||busy} onClick={run}>Run one check</button>{account.grant&&<button className="ws-action-quiet" disabled={busy} onClick={revoke}>Revoke permission</button>}</div><p className="ws-agent-status"><i className={running?'is-running':''}/>{pending?'Agent is waiting for your approval.':running?(session.background?'Background practice is enabled. Checks continue after you close this page.':'Agent checks every eight seconds while this workspace stays open.'):'Agent is paused. Run one check or start the agent.'}</p><div className="ws-practice-background"><strong>Keep practicing while you’re away</strong><p>Optional background checks wake about every 15 minutes and may be delayed. Only fake funds are used. Approval mode keeps waiting for you; pause or revoke stops future checks.</p><button className="ws-action-secondary" disabled={busy||!running||!backgroundAvailable} onClick={()=>void command({action:'background',enabled:!session.background})}>{session.background?'Disable background practice':'Enable background practice'}</button><button className="ws-action-quiet" disabled={busy} onClick={()=>void load()}>Refresh saved session</button>{!backgroundAvailable&&<small>Background runner unavailable. Foreground practice still works.</small>}</div><small>Scheduled buys follow the simulated clock, which advances with elapsed time and your test-clock controls.</small></>:<p>Reviewed strategy retained. Live activation is unavailable; no wallet request or real purchase will be made.</p>}
  </div>}
  <div className="ws-strategy-trail"><div className="ws-account-head"><h3>Practice decision trail</h3><button className="ws-action-secondary" onClick={download} disabled={!receipts.length}>Download practice receipts</button></div>{!receipts.length&&<p>Authorize practice and run a check to see the agent’s reasoning here.</p>}{receipts.map(r=><details key={r.id}><summary><strong>{r.outcome==='awaiting_approval'?'Your approval needed':r.outcome==='simulated_fill'?'Practice purchase completed':r.outcome==='held'?'Agent held':'Declined'}</strong> · {r.symbol} · {money(r.amountCents)}<small>{new Date(r.createdAt).toLocaleString()}</small></summary><p>{r.why}</p><p>{r.trigger==='background'?'Background agent check':r.trigger==='foreground'?'Workspace agent check':'Manual practice check'}</p><p>Practice · strategy v{r.strategyVersion} · mandate v{r.mandateVersion}. {r.outcome==='simulated_fill'?'Simulated balance updated. No transaction hash exists.':'No purchase made.'}</p>{r.checks.map(c=><div className="ws-receipt-check" key={c.name}><b>{c.passed?'PASS':'FAIL'}</b><span><strong>{c.name}</strong><small>{c.detail}</small></span></div>)}{r.outcome==='awaiting_approval'&&mode==='practice'&&<div className="ws-chain-tools"><button className="ws-action-primary" disabled={busy} onClick={()=>approve(r)}>Approve exact practice purchase</button><button className="ws-action-secondary" disabled={busy} onClick={()=>decline(r.id)}>Decline</button></div>}</details>)}</div>
 </section>;
}

