'use client';
import {useEffect,useRef,useState} from 'react';
import {Wallet,Eye,Plus,ArrowUpRight} from 'lucide-react';
import useBrowserWallets from './use-browser-wallets';
import {switchRobinhood,type WalletProvider} from '@/lib/browser-wallet';
export default function WalletOnboarding({onAddress,onProvider,disabled}:{onAddress:(address:string)=>void;onProvider:(provider:WalletProvider|null)=>void;disabled:boolean}){
 const [mode,setMode]=useState<'connect'|'watch'|'create'>('connect'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[connected,setConnected]=useState(false),[chainId,setChainId]=useState<string|null>(null);
 const wallets=useBrowserWallets();const [walletId,setWalletId]=useState('');const selected=wallets.find(w=>w.id===walletId);const provider=selected?.provider;const providerCallback=useRef(onProvider);providerCallback.current=onProvider;
 const generation=useRef(0),callback=useRef(onAddress);callback.current=onAddress;
 useEffect(()=>{const p=provider;let alive=true;let read=0;
  const readChain=async()=>{const current=++read;try{const chain=await p?.request({method:'eth_chainId'});if(alive&&current===read)setChainId(typeof chain==='string'&&/^0x[0-9a-f]+$/i.test(chain)?BigInt(chain).toString():null);}catch{if(alive&&current===read)setChainId(null);}};
  setChainId(null);if(p)void readChain();
  const changed=()=>{generation.current++;setBusy(false);setConnected(false);providerCallback.current(null);callback.current('');setMessage('Wallet account changed. Connect again to choose the current account.');};
  p?.on?.('accountsChanged',changed);p?.on?.('chainChanged',readChain);return()=>{alive=false;generation.current++;p?.removeListener?.('accountsChanged',changed);p?.removeListener?.('chainChanged',readChain);};
 },[provider]);
 async function switchNetwork(){const ticket=++generation.current;setBusy(true);setMessage('');try{if(!provider||!connected)throw Error('Connect a wallet first.');await switchRobinhood(provider);if(ticket!==generation.current)return;setChainId('4663');setMessage('Your wallet is now on Robinhood Chain. No funds moved and no spending permission was granted.');}catch{if(ticket===generation.current)setMessage('Network switch canceled or unavailable. You can choose Robinhood Chain manually in your wallet.');}finally{if(ticket===generation.current)setBusy(false);}}
 async function connect(){const ticket=++generation.current;setBusy(true);setMessage('');try{const p=provider;if(!p)throw Error('Choose a detected wallet first. If none appears, open this page in a browser with your wallet installed.');const accounts=await p.request({method:'eth_requestAccounts'});if(!Array.isArray(accounts)||typeof accounts[0]!=='string'||!/^0x[0-9a-f]{40}$/i.test(accounts[0]))throw Error('No wallet account was selected.');if(ticket!==generation.current)return;providerCallback.current(p);callback.current(accounts[0]);setConnected(true);setMessage('Address selected. Ownership verification is a separate message signature below; no spending permission was granted.');}catch(e){if(ticket===generation.current)setMessage(e instanceof Error&&e.message.startsWith('Choose a detected')?e.message:'Connection canceled or unavailable. You can try again or use a watch-only address.');}finally{if(ticket===generation.current)setBusy(false);}}
 function select(next:typeof mode){generation.current++;setBusy(false);setMessage('');setConnected(false);setMode(next);providerCallback.current(null);callback.current('');}
 return <div className="ws-wallet-onboarding"><span className="ws-label">YOUR WALLET / YOUR CHOICE</span><h3>Start with an address. Keep control.</h3><p>Stock Steward never asks you to paste a private key or recovery phrase.</p><div className="ws-wallet-options">
 <button type="button" aria-pressed={mode==='connect'} disabled={disabled||busy} onClick={()=>select('connect')}><Wallet size={19}/><strong>Connect your wallet</strong><small>Available · your wallet keeps the keys</small></button>
 <button type="button" aria-pressed={mode==='watch'} disabled={disabled||busy} onClick={()=>select('watch')}><Eye size={19}/><strong>Watch an address</strong><small>Available · no signature required</small></button>
 <button type="button" aria-pressed={mode==='create'} disabled={disabled||busy} onClick={()=>select('create')}><Plus size={19}/><strong>Create a wallet</strong><small>Planned · recovery setup comes first</small></button>
 </div><div className="ws-wallet-choice" key={mode}>{mode==='connect'?<>{wallets.length>0&&<label className="ws-wallet-picker">Choose a wallet<select value={walletId} disabled={disabled||busy} onChange={e=>{generation.current++;setWalletId(e.target.value);setConnected(false);setMessage('');providerCallback.current(null);callback.current('');}}><option value="">Select a detected wallet</option>{wallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>}{!wallets.length&&<p>No browser wallet detected. Open this page in your wallet’s browser or a browser with an EVM wallet extension. You can use “Watch an address” without a wallet.</p>}<p>Choose your account in your wallet’s connection prompt. This shares its public address. Verify control below only when you are ready to sign the displayed ownership message.</p><button type="button" disabled={disabled||busy||!provider} onClick={connected?()=>{generation.current++;setConnected(false);providerCallback.current(null);callback.current('');setMessage('Disconnected from this view. Saved receipts remain.');}:connect}>{busy?'Waiting for your wallet…':connected?'Disconnect from this view':'Connect browser wallet'} <ArrowUpRight size={16}/></button><button className="ws-recheck" type="button" disabled={disabled||busy||!provider||!connected||chainId==='4663'} onClick={switchNetwork}>{!connected?'Connect wallet to select a network':chainId==='4663'?'Wallet already on Robinhood Chain':'Switch wallet to Robinhood Chain'}</button><p>Steward reads Robinhood Chain automatically. This control changes only your connected wallet’s network; it does not move funds.</p><small>Wallet labels are supplied by installed extensions. Network setup does not fund your wallet or authorize a trade.</small></>:mode==='watch'?<p>Paste any public wallet address below to inspect holdings and route evidence. Watching an address does not let Steward spend from it or prove that you own it.</p>:<><strong>Wallet creation inside Stock Steward is not available yet.</strong><p>You can create a wallet in your own wallet app and return to “Connect your wallet.” Creating a wallet does not require funding. Our built-in flow will need tested recovery and key protection before it launches.</p></>}{message&&<p role="status">{message}</p>}</div></div>;
}

