'use client';
import {useEffect,useRef,useState} from 'react';
import {Wallet,Eye,Plus,ArrowUpRight} from 'lucide-react';
import WalletConnect from './wallet-connect';
import {switchRobinhood,type WalletProvider} from '@/lib/browser-wallet';
export default function WalletOnboarding({onAddress,onProvider,disabled}:{onAddress:(address:string)=>void;onProvider:(provider:WalletProvider|null)=>void;disabled:boolean}){
 const [mode,setMode]=useState<'connect'|'watch'|'create'>('connect'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[connected,setConnected]=useState(false),[chainId,setChainId]=useState<string|null>(null);
 const [provider,setProvider]=useState<WalletProvider|null>(null);const providerCallback=useRef(onProvider);providerCallback.current=onProvider;
 const generation=useRef(0),callback=useRef(onAddress);callback.current=onAddress;
 useEffect(()=>{const p=provider;let alive=true;let read=0;
  const readChain=async()=>{const current=++read;try{const chain=await p?.request({method:'eth_chainId'});if(alive&&current===read)setChainId(typeof chain==='string'&&/^0x[0-9a-f]+$/i.test(chain)?BigInt(chain).toString():null);}catch{if(alive&&current===read)setChainId(null);}};
  setChainId(null);if(p)void readChain();
  const changed=()=>{generation.current++;setBusy(false);setConnected(false);providerCallback.current(null);callback.current('');setMessage('Wallet account changed. Connect again to choose the current account.');};
  p?.on?.('accountsChanged',changed);p?.on?.('chainChanged',readChain);return()=>{alive=false;generation.current++;p?.removeListener?.('accountsChanged',changed);p?.removeListener?.('chainChanged',readChain);};
 },[provider]);
 async function switchNetwork(){const ticket=++generation.current;setBusy(true);setMessage('');try{if(!provider||!connected)throw Error('Connect a wallet first.');await switchRobinhood(provider);if(ticket!==generation.current)return;setChainId('4663');setMessage('Your wallet is now on Robinhood Chain. No funds moved and no spending permission was granted.');}catch{if(ticket===generation.current)setMessage('Network switch canceled or unavailable. You can choose Robinhood Chain manually in your wallet.');}finally{if(ticket===generation.current)setBusy(false);}}
 function select(next:typeof mode){generation.current++;setBusy(false);setMessage('');setConnected(false);setMode(next);providerCallback.current(null);callback.current('');}
 return <div className="ws-wallet-onboarding"><span className="ws-label">YOUR WALLET / YOUR CHOICE</span><h3>Start with an address. Keep control.</h3><p>Stock Steward never asks you to paste a private key or recovery phrase.</p><div className="ws-wallet-options">
 <button type="button" aria-pressed={mode==='connect'} disabled={disabled||busy} onClick={()=>select('connect')}><Wallet size={19}/><strong>Connect your wallet</strong><small>Available · your wallet keeps the keys</small></button>
 <button type="button" aria-pressed={mode==='watch'} disabled={disabled||busy} onClick={()=>select('watch')}><Eye size={19}/><strong>Watch an address</strong><small>Available · no signature required</small></button>
 <button type="button" aria-pressed={mode==='create'} disabled={disabled||busy} onClick={()=>select('create')}><Plus size={19}/><strong>Create a wallet</strong><small>Planned · recovery setup comes first</small></button>
 </div><div className="ws-wallet-choice" key={mode}>{mode==='connect'?<><p>Click Connect browser wallet, then choose a wallet in the popup. Its account connection prompt opens immediately. Ownership verification remains a separate message signature.</p>{connected?<button type="button" disabled={disabled||busy} onClick={()=>{generation.current++;setConnected(false);setProvider(null);providerCallback.current(null);callback.current('');setMessage('Disconnected from this view. Saved receipts remain.');}}>Disconnect from this view</button>:<WalletConnect disabled={disabled||busy} onConnected={(p,address)=>{generation.current++;setProvider(p);providerCallback.current(p);callback.current(address);setConnected(true);setMessage('Wallet connected. No signature or spending permission was requested.');}}/>}<button className="ws-recheck" type="button" disabled={disabled||busy||!provider||!connected||chainId==='4663'} onClick={switchNetwork}>{!connected?'Connect wallet to select a network':chainId==='4663'?'Wallet already on Robinhood Chain':'Switch wallet to Robinhood Chain'}</button><p>Steward reads Robinhood Chain automatically. This control changes only your connected wallet’s network; it does not move funds.</p><small>Wallet labels are supplied by installed extensions. Network setup does not fund your wallet or authorize a trade.</small></>:mode==='watch'?<p>Paste any public wallet address below to inspect holdings and route evidence. Watching an address does not let Steward spend from it or prove that you own it.</p>:<><strong>Wallet creation inside Stock Steward is not available yet.</strong><p>You can create a wallet in your own wallet app and return to “Connect your wallet.” Creating a wallet does not require funding. Our built-in flow will need tested recovery and key protection before it launches.</p></>}{message&&<p role="status">{message}</p>}</div></div>;
}


